(function(d){String.prototype.format||(String.prototype.format=function(){var a=arguments;return this.replace(/\{\{|\}\}|\{(\d+)\}/g,function(d,h){return"{{"===d?"{":"}}"===d?"}":a[h]})});d.jgrid.odataHelper={resolveJsonReferences:function(d,g){function h(b,d,a){if("object"!==typeof b||!b)return b;if("[object Array]"===Object.prototype.toString.call(b)){for(f=0;f<b.length;f++){if("object"!==typeof b[f]||!b[f])return b[f];b[f]=b[f].$ref?h(b[f],f,b):h(b[f],d,b)}return b}if(b.$ref){m=b.$ref;if(c[m])return c[m];
g.push([a,d,m])}else{if(b.$id){d=b.$id;delete b.$id;if(b.$values)b=b.$values.map(h);else for(var e in b)b.hasOwnProperty(e)&&(b[e]=h(b[e],e,b));c[d]=b}return b}}var f,m,c={};g=g||[];"string"===typeof d&&(d=JSON.parse(d));d=h(d);for(f=0;f<g.length;f++)m=g[f],m[0][m[1]]=c[m[2]];return d},convertXmlToJson:function(a){var g={},h,f,m,c;if(!a)return null;if(1===a.nodeType){if(0<a.attributes.length)for(g["@attributes"]={},h=0;h<a.attributes.length;h++)f=a.attributes.item(h),g["@attributes"][f.nodeName]=
f.nodeValue}else 3===a.nodeType?g=a.nodeValue:a.nodeType||(g=a);if(a.hasChildNodes&&a.hasChildNodes())for(h=0;h<a.childNodes.length;h++){f=a.childNodes.item(h);if(3===f.nodeType)return f.nodeValue;m=f.nodeName;void 0===g[m]?g[m]=d.jgrid.odataHelper.convertXmlToJson(f):(void 0===g[m].push&&(c=g[m],g[m]=[],g[m].push(c)),g[m].push(d.jgrid.odataHelper.convertXmlToJson(f)))}return d.isEmptyObject(g)?null:g},cmTemplateFormatter:function(a,g,h){if(!g.colModel.odataexpand||"json"===g.colModel.odataexpand)return"xml"===
this.p.datatype&&(a=d(h).filter(function(){return this.localName.toLowerCase()===g.colModel.name.toLowerCase()}),a=d.jgrid.odataHelper.convertXmlToJson(a[0])),JSON.stringify(a,null,1);if("link"===g.colModel.odataexpand)return a="xml"!==this.p.datatype?h[this.p.jsonReader.id]:function(a){return d(h).filter(function(){return this.localName.toLowerCase()===a}).text()}(this.p.xmlReader.id.toLowerCase()),'<a href="{0}({1})/{2}" target="_self" data-id="{1}">{2}</a>'.format(this.p.url,a,g.colModel.name)},
loadError:function(a,g,h){var f=a.status,m=h;if(!a.responseJSON)if(a.responseXML)a.responseText=a.responseText.replace(/<(\/?)([^:>\s]*:)?([^>]+)>/g,"<$1$3>"),a.responseXML=d.parseXML(a.responseText),a.responseJSON=d.jgrid.odataHelper.convertXmlToJson(a.responseXML);else if(a.responseText)try{a.responseJSON=d.parseJSON(a.responseText)}catch(c){}if(a.responseJSON){if(a=a.responseJSON["@odata.error"]||a.responseJSON["odata.error"]||a.responseJSON.error)a.innererror?a.innererror.internalexception?(g=
a.innererror.internalexception.message,m=a.innererror.internalexception.stacktrace||""):(g=a.innererror.message,m=a.innererror.stacktrace||""):(g=a.message.value||a.message,m=a.stacktrace||"")}else h&&d.isPlainObject(h)&&(g=h.message,m=h.stack,f=h.code);return"<div>Status/error code: "+f+"</div><div>Message: "+g+'</div><div style="font-size: 0.8em;">'+m+"</div><br/>"}};d.jgrid.cmTemplate.odataComplexType={editable:!1,formatter:d.jgrid.odataHelper.cmTemplateFormatter};d.jgrid.cmTemplate.odataNavigationProperty=
{editable:!1,formatter:d.jgrid.odataHelper.cmTemplateFormatter};d.jgrid.extend({odataInit:function(a){function g(c,b,r,a){var e,k;if(b&&(r||"nu"===a||"nn"===a)){if(r)for(e=0;e<c.colModel.length;e++)if(k=c.colModel[e],k.name===b){if(!1===k.odata||k.odataunformat&&(b=d.isFunction(k.odataunformat)?k.odataunformat(b,r,a):k.odataunformat,!b))return;k.searchrules&&(k.searchrules.integer||k.searchrules.number||k.searchrules.date)?k.searchrules&&k.searchrules.date&&(r=(new Date(r)).toISOString()):r="'"+r+
"'";break}switch(a){case "in":case "cn":return"indexof("+b+",tolower("+r+")) gt -1";case "ni":case "nc":return"indexof("+b+",tolower("+r+")) eq -1";case "bw":return"startswith("+b+","+r+") eq true";case "bn":return"startswith("+b+","+r+") eq false";case "ew":return"endswith("+b+","+r+") eq true";case "en":return"endswith("+b+","+r+") eq false";case "nu":return b+" eq null";case "nn":return b+" ne null";default:return b+" "+a+" "+r}}}function h(c,b){var d,a,e="";if(c.groups&&c.groups.length){for(d=
0;d<c.groups.length;d++)e+="("+h(c.groups[d],b)+")",d<c.groups.length-1&&(e+=" "+c.groupOp.toLowerCase()+" ");c.rules&&c.rules.length&&(e+=" "+c.groupOp.toLowerCase()+" ")}if(c.rules.length)for(d=0;d<c.rules.length;d++)a=c.rules[d],(a=g(b,a.field,a.data,a.op))&&(e+=a+" "+c.groupOp.toLowerCase()+" ");return e=e.trim().replace(/\s(and|or)$/,"").trim()}function f(c,b,a){var f={$top:a.rows,$skip:(parseInt(a.page,10)-1)*c.rowNum,$format:"xml"===b.datatype?"atom":"json"},e=c.colModel.filter(function(b){return"json"===
b.odataexpand||"subgrid"===b.odataexpand});0<e.length&&(f.$expand=e.reduce(function(b,c){return b+","+c.name},"").substring(1));"jsonp"===b.datatype&&(f.$callback=b.callback);b.count&&(f.$count=!0);b.inlinecount&&(f.$inlinecount="allpages");a.sidx&&(f.$orderby=a.sidx+" "+a.sord);if(!a._search)return f;a.filters?(b=d.parseJSON(a.filters),c=h(b,c),0<c.length&&(f.$filter=c)):f.$filter=g(c,a.searchField,a.searchString,a.searchOper);return f}function m(c,b){var a={datatype:b.datatype,jsonpCallback:b.callback};
d.extend(c,{serializeGridData:function(a){a=f(c,b,a);return this.p.odataPostData=a},ajaxGridOptions:a,mtype:"GET",url:b.odataurl},a);a={contentType:"application/"+("jsonp"===b.datatype?"json":b.datatype)+";charset=utf-8",datatype:"jsonp"===b.datatype?"json":b.datatype};c.inlineEditing=d.extend(!0,{beforeSaveRow:function(a,c,d){"edit"===a.extraparam.oper?(a.url=b.odataurl,a.mtype=b.odataverbs.inlineEditingEdit,a.url+="("+c+")"):(a.url=b.odataurl,a.mtype=b.odataverbs.inlineEditingAdd);return!0},serializeSaveData:function(b){return JSON.stringify(b)},
ajaxSaveOptions:a},c.inlineEditing||{});d.extend(c.formEditing,{onclickSubmit:function(a,d,e){"add"===e?(a.url=b.odataurl,a.mtype=b.odataverbs.formEditingAdd):"edit"===e&&(a.url=b.odataurl+"("+d[c.id+"_id"]+")",a.mtype=b.odataverbs.formEditingEdit);return d},ajaxEditOptions:a,serializeEditData:function(a){return JSON.stringify(a)}});d.extend(c.formDeleting,{url:b.odataurl,mtype:"DELETE",serializeDelData:function(a){return""},onclickSubmit:function(a,b){a.url+="("+b+")";return""},ajaxDelOptions:a});
a=(a=c.colModel.filter(function(a){return!!a.key})[0])?a.name:c.sortname||"id";if("xml"===b.datatype){b.annotations&&d.extend(!0,c,{loadBeforeSend:function(a){a.setRequestHeader("Prefer",'odata.include-annotations="*"')}});var g=b.useXmlSerializer?">feed":"ArrayOf"+b.entityType,e=b.useXmlSerializer?">entry":b.entityType,k=b.useXmlSerializer?">content>properties":"",h=b.useXmlSerializer?">link feed":"";d.extend(!0,c,{xmlReader:{root:function(a){a=d(g,a).get(0);a.innerHTML=a.innerHTML.replace(/<(\/?)([^:>\s]*:)?([^>]+)>/g,
"<$1$3>");return a},row:function(a){a=d(e,a);if(c.odataPostData.$expand){var b,f,g=a.length,l;for(b=0;b<g;b++)f=d(h,a[b]).has("title:not(:empty)"),l=f.children("title").text(),f=f.find(e+k).get(0).childNodes,0<f.length&&d(k,a[b]).append(d("<"+l+">").append(f).get(0))}return a},cell:function(a){return d(k,a).get(0).childNodes},records:function(a){return d(g+e,a).length},page:function(a){return Math.ceil((c.odataPostData.$skip+c.rowNum)/c.rowNum)},total:function(a){a=d(g+e,a).length;return Math.ceil((c.odataPostData.$skip+
c.rowNum)/c.rowNum)+(0<a?1:0)},repeatitems:!0,userdata:b.useXmlSerializer?"userdata":"ArrayOfUserData UserData",id:a}})}else b.annotations?d.extend(!0,c,{loadBeforeSend:function(a){a.setRequestHeader("Prefer",'odata.include-annotations="*"')},jsonReader:{root:"value",repeatitems:!1,records:function(a){return a[b.annotationName].records},page:function(a){return a[b.annotationName].page},total:function(a){return a[b.annotationName].total},userdata:function(a){return a[b.annotationName].userdata},id:a}}):
d.extend(!0,c,{jsonReader:{root:"value",repeatitems:!1,records:function(a){return a["odata.count"]||a["@odata.count"]},page:function(a){var b;a["odata.nextLink"]?b=parseInt(a["odata.nextLink"].split("skip=")[1],10):(b=c.odataPostData.$skip+c.rowNum,a=a["odata.count"]||a["@odata.count"],b>a&&(b=a));return Math.ceil(b/c.rowNum)},total:function(a){return Math.ceil(parseInt(a["odata.count"]||a["@odata.count"],10)/c.rowNum)},userdata:"userdata",id:a}})}return this.each(function(){var c=this,b=d(c),f=c.p;
if(c.grid&&f){var g=d.extend(!0,{gencolumns:!1,odataurl:f.url,datatype:"json",entityType:null,annotations:!1,annotationName:"@jqgrid.GridModelAnnotate",useXmlSerializer:!0,odataverbs:{inlineEditingAdd:"POST",inlineEditingEdit:"PATCH",formEditingAdd:"POST",formEditingEdit:"PUT"}},a||{});"jsonp"===g.datatype&&(g.callback="jsonpCallback");if(g.entityType){g=!g.version||4>g.version?d.extend(!0,{inlinecount:!0,count:!1},g||{}):d.extend(!0,{inlinecount:!1,count:!0},g||{});if(g.gencolumns){var e=d.extend(!0,
{parsecolfunc:null,parsemetadatafunc:null,successfunc:null,errorfunc:null,async:!1,entityType:null,metadatatype:a.datatype||"xml",metadataurl:(a.odataurl||f.url)+"/$metadata"},a||{});e.async&&(e.successfunc=function(){c.grid.hDiv&&(c.grid.hDiv.loading=!1);b.trigger("reloadGrid")},c.grid.hDiv&&(c.grid.hDiv.loading=!0));b.jqGrid("odataGenColModel",e)}m(f,g)}else d.isFunction(g.errorfunc)&&g.errorfunc({},"entityType cannot be empty")}})},odataGenColModel:function(a){function g(a,c){var f=[],e,g,h,m,
t,q,n,l={};t=d("Schema",a).attr("Namespace")+".";e=d('EntityType[Name="'+c+'"]',a).find("Property,NavigationProperty");h=(g=d('EntityType[Name="'+c+'"] Key PropertyRef',a))&&0<g.length?g.first().attr("Name"):"";e&&e.each(function(a,b){d.each(b.attributes,function(){l[this.name]=this.value});m=l.Name===h;q="Property"===b.tagName&&!!t&&0<=l.Type.indexOf(t);n="NavigationProperty"===b.tagName;f.push(d.extend({iskey:m,isComplex:q,isNavigation:n},l))});return f}var h=this[0],f=h.p,m=d(h),c=d.extend(!0,
{parsecolfunc:null,parsemetadatafunc:null,successfunc:null,errorfunc:null,entityType:null,metadataurl:f.url+"/$metadata",metadatatype:"xml",expandable:"link",async:!1},a||{});"jsonp"===c.metadatatype&&(c.callback="jsonpCallback");c.entityType?d.ajax({url:c.metadataurl,type:"GET",dataType:c.metadatatype,jsonpCallback:c.callback,async:c.async,cache:!1}).done(function(a,h,v){var e=0,k=0,p,u,t,q;"xml"!==c.metadatatype&&(a=d.jgrid.odataHelper.resolveJsonReferences(a));var n=m.triggerHandler("jqGridODataParseMetadata",
a);void 0===n&&d.isFunction(c.parsemetadatafunc)&&(n=c.parsemetadatafunc(a,h,v));if(void 0===n){if("xml"===c.metadatatype)p=g(a,c.entityType);else{q=a;for(var l=c.entityType,e=[],w,x,y,k=0;k<q.SchemaElements.length;k++)if(q.SchemaElements[k].Name===l){p=q.SchemaElements[k].DeclaredProperties;q.SchemaElements[k].NavigationProperties&&(p=p.concat(q.SchemaElements[k].NavigationProperties));t=q.SchemaElements[k].DeclaredKey;u=q.SchemaElements[k].Namespace;break}t=t&&0<t.length?t[0].Name:"";if(p)for(k=
0;k<p.length;k++)q=p[k].Name,x=q===t,w=p[k].Type.IsNullable,l=p[k].Type.Definition.Namespace+"."+p[k].Type.Definition.Name,y=!!u&&0<=l.indexOf(u),e.push({Name:q,Type:l,Nullable:w,iskey:x,isComplex:y,isNavigation:!1});p=e}l=p;if(0===l.length)d.isFunction(c.errorfunc)&&c.errorfunc({data:a,status:h,xhr:v},"parse $metadata error");else if(n=m.triggerHandler("jqGridODataParseColumns",l),void 0===n&&d.isFunction(c.parsecolfunc)&&(n=c.parsecolfunc(l)),void 0===n)for(n=[],e=0;e<l.length;e++)p=0<="Edm.Int16,Edm.Int32,Edm.Int64".indexOf(l[e].Type),
u=0<="Edm.Decimal,Edm.Double,Edm.Single".indexOf(l[e].Type),t=0<="Edm.Byte,Edm.SByte".indexOf(l[e].Type),k=l[e].Type&&0<=l[e].Type.indexOf("Edm.")&&(0<=l[e].Type.indexOf("Date")||0<=l[e].Type.indexOf("Time")),q=l[e].isComplex?"odataComplexType":l[e].isNavigation?"odataNavigationProperty":p?"integerStr":u?"numberStr":t?"booleanCheckbox":"text",n.push(d.extend({label:l[e].Name,name:l[e].Name,index:l[e].Name,editable:!l[e].isNavigation&&!l[e].iskey,searchrules:{integer:p,number:u,date:k,required:!l[e].Nullable||
"false"===l[e].Nullable},editrules:this.searchrules,searchtype:p?"integer":u?"number":k?"datetime":t?"checkbox":"text",inputtype:this.searchtype,edittype:this.searchtype,key:l[e].iskey,odataexpand:l[e].isNavigation||l[e].isComplex?c.expandable:null},d.jgrid.cmTemplate[q]))}if(n){for(e=0;e<f.colModel.length;e++)for(k=0;k<n.length;k++)if(n[k].name===f.colModel[e].name){d.extend(!0,n[k],f.colModel[e]);break}f.colModel=n;d.isFunction(c.successfunc)&&c.successfunc()}else d.isFunction(c.errorfunc)&&c.errorfunc({data:a,
status:h,xhr:v},"parse $metadata error")}).fail(function(a,f,g){if(d.isFunction(c.errorfunc)){var e=d.jgrid.odataHelper.loadError(a,f,g);c.errorfunc({xhr:a,error:f,code:g},e)}}):d.isFunction(c.errorfunc)&&c.errorfunc({},"entityType cannot be empty")}})})(jQuery);
