(function(e){String.prototype.format||(String.prototype.format=function(){var a=arguments;return this.replace(/\{\{|\}\}|\{(\d+)\}/g,function(e,c){return"{{"===e?"{":"}}"===e?"}":a[c]})});e.jgrid.odataHelper={resolveJsonReferences:function(a,e){function c(b,a,q){if("object"!==typeof b||!b)return b;if("[object Array]"===Object.prototype.toString.call(b)){for(d=0;d<b.length;d++){if("object"!==typeof b[d]||!b[d])return b[d];b[d]=b[d].$ref?c(b[d],d,b):c(b[d],a,b)}return b}if(b.$ref){h=b.$ref;if(l[h])return l[h];
e.push([q,a,h])}else{if(b.$id){a=b.$id;delete b.$id;if(b.$values)b=b.$values.map(c);else for(var k in b)b.hasOwnProperty(k)&&(b[k]=c(b[k],k,b));l[a]=b}return b}}var d,h,l={};e=e||[];"string"===typeof a&&(a=JSON.parse(a));a=c(a);for(d=0;d<e.length;d++)h=e[d],h[0][h[1]]=l[h[2]];return a},convertXmlToJson:function(a){var f={},c,d,h,l;if(!a)return null;if(1===a.nodeType){if(0<a.attributes.length)for(f["@attributes"]={},c=0;c<a.attributes.length;c++)d=a.attributes.item(c),f["@attributes"][d.nodeName]=
d.nodeValue}else 3===a.nodeType?f=a.nodeValue:a.nodeType||(f=a);if(a.hasChildNodes&&a.hasChildNodes())for(c=0;c<a.childNodes.length;c++){d=a.childNodes.item(c);if(3===d.nodeType)return d.nodeValue;h=d.nodeName;void 0===f[h]?f[h]=e.jgrid.odataHelper.convertXmlToJson(d):(void 0===f[h].push&&(l=f[h],f[h]=[],f[h].push(l)),f[h].push(e.jgrid.odataHelper.convertXmlToJson(d)))}return e.isEmptyObject(f)?null:f},cmTemplateFormatter:function(a,f,c){var d;if(!a)return"";f.colModel.odataexpand&&"link"!==f.colModel.odataexpand?
"subgrid"===f.colModel.odataexpand?(a="xml"!==this.p.datatype?c[this.p.jsonReader.id]:function(a){return e(c).filter(function(){return this.localName&&this.localName.toLowerCase()===a}).text()}(this.p.xmlReader.id.toLowerCase()),d='<a style="cursor:pointer" data-id="{0}" onclick=\'$("#{2}").jqGrid("setGridParam", { odataActiveEntitySet: "{1}" });$("#{2}").jqGrid("expandSubGridRow", {0});return false;\'>{1}</a>'.format(a,f.colModel.name,f.gid)):"json"===f.colModel.odataexpand&&("xml"===this.p.datatype&&
(a=e(c).filter(function(){return this.localName.toLowerCase()===f.colModel.name.toLowerCase()}),a=e.jgrid.odataHelper.convertXmlToJson(a[0])),d=JSON.stringify(a,null,1)):"xml"!==this.p.datatype?c["@odata.editLink"]&&c[f.colModel.name+"@odata.navigationLink"]?(a=c[f.colModel.name+"@odata.navigationLink"],d='<a href="{0}/{1}" target="_self" data-id="{1}">{2}</a>'.format(this.p.odataBaseUrl,a,f.colModel.name)):(a=c[this.p.jsonReader.id],d='<a href="{0}({1})/{2}" target="_self" data-id="{1}">{2}</a>'.format(this.p.url,
a,f.colModel.name)):(a=function(a){return e(c).filter(function(){return this.localName&&this.localName.toLowerCase()===a}).text()}(this.p.xmlReader.id.toLowerCase()),d='<a href="{0}({1})/{2}" target="_self" data-id="{1}">{2}</a>'.format(this.p.url,a,f.colModel.name));return d},loadError:function(a,f,c){var d=a.status,h=c;if(!a.responseJSON)if(a.responseXML)a.responseText=a.responseText.replace(/<(\/?)([^:>\s]*:)?([^>]+)>/g,"<$1$3>"),a.responseXML=e.parseXML(a.responseText),a.responseJSON=e.jgrid.odataHelper.convertXmlToJson(a.responseXML);
else if(a.responseText)try{a.responseJSON=e.parseJSON(a.responseText)}catch(l){}if(a.responseJSON){if(a=a.responseJSON["@odata.error"]||a.responseJSON["odata.error"]||a.responseJSON.error)a.innererror?a.innererror.internalexception?(f=a.innererror.internalexception.message,h=a.innererror.internalexception.stacktrace||""):(f=a.innererror.message,h=a.innererror.stacktrace||""):(f=a.message.value||a.message,h=a.stacktrace||"")}else c&&e.isPlainObject(c)&&(f=c.message,h=c.stack,d=c.code);return"<div>Status/error code: "+
d+"</div><div>Message: "+f+'</div><div style="font-size: 0.8em;">'+h+"</div><br/>"}};e.jgrid.cmTemplate.odataComplexType={editable:!1,formatter:e.jgrid.odataHelper.cmTemplateFormatter};e.jgrid.cmTemplate.odataNavigationProperty={editable:!1,formatter:e.jgrid.odataHelper.cmTemplateFormatter};e.jgrid.extend({parseColumns:function(a,f){for(var c=0,d,h,l,b,n,q=[],k,c=0;c<a.length;c++)d=0<="Edm.Int16,Edm.Int32,Edm.Int64".indexOf(a[c].Type),h=0<="Edm.Decimal,Edm.Double,Edm.Single".indexOf(a[c].Type),b=
0<="Edm.Byte,Edm.SByte".indexOf(a[c].Type),l=a[c].Type&&0<=a[c].Type.indexOf("Edm.")&&(0<=a[c].Type.indexOf("Date")||0<=a[c].Type.indexOf("Time")),n=a[c].isComplex?"odataComplexType":a[c].isNavigation?"odataNavigationProperty":d?"integerStr":h?"numberStr":b?"booleanCheckbox":"text",k={integer:d,number:h,date:l,required:!a[c].Nullable||"false"===a[c].Nullable},d=d?"integer":h?"number":l?"datetime":b?"checkbox":"text",h=a[c].isNavigation||a[c].isComplex?'<span class="ui-icon ui-icon-arrowreturn-1-s" style="display:inline-block;vertical-align:middle;"></span>'+
a[c].Name:a[c].Name,q.push(e.extend({label:h,name:a[c].Name,index:a[c].Name,editable:!a[c].isNavigation&&!a[c].iskey,searchrules:k,editrules:k,searchtype:d,inputtype:d,edittype:d,key:a[c].iskey,odataexpand:a[c].isNavigation||a[c].isComplex?f:null,odatatype:a[c].isNavigation?"navigation":a[c].isComplex?"complex":"simple"},e.jgrid.cmTemplate[n]));return q},parseMetadata:function(a,f){function c(a){var c,b,n,q,k,g,m,d,f,r,p,u={},v={};g=e("Schema",a).attr("Namespace")+".";e("EntityContainer EntitySet",
a).each(function(b,g){v[e(g).attr("EntityType")]=e(g).attr("Name")});e("EntityType",a).each(function(){b=e(this).find("Property,NavigationProperty");q=(n=e("Key PropertyRef",this))&&0<n.length?n.first().attr("Name"):"";r=e(this).attr("Name");b&&(c=[],b.each(function(b,a){p={};e.each(a.attributes,function(){p[this.name]=this.value});f=p.Type;k=p.Name===q;d="NavigationProperty"===a.tagName&&0<=f.indexOf("Collection");m="Property"===a.tagName&&!!g&&0<=f.indexOf(g)||"NavigationProperty"===a.tagName&&
0>f.indexOf("Collection");0===f.indexOf("Collection(")&&(f=f.replace("Collection(","").slice(0,-1));f=f.replace(g,"");c.push(e.extend({iskey:k,isComplex:m,isNavigation:d},p))}),u[v[g+r]]=c,u[r]=c)});return u}function d(a){var e,b,n,c,k,g,m,d,f,r,p={};for(d=0;d<a.SchemaElements.length;d++)if(b=a.SchemaElements[d].DeclaredProperties,a.SchemaElements[d].NavigationProperties&&(b=b.concat(a.SchemaElements[d].NavigationProperties)),n=(e=a.SchemaElements[d].DeclaredKey)&&0<e.length?e[0].Name:"",r=a.SchemaElements[d].Namespace,
c=a.SchemaElements[d].Name,b){e=[];for(d=0;d<b.length;d++)m=b[d].Name===n,g=b[d].Type.IsNullable,k=b[d].Type.Definition.Namespace+"."+b[d].Type.Definition.Name,f=!!r&&0<=k.indexOf(r),e.push({Name:b[d].Name,Type:k,Nullable:g,iskey:m,isComplex:f,isNavigation:!1});p[c]=e}return p}return"xml"===f?c(a):d(a)},odataInit:function(a){function f(b,a,c,d){var g,m;if(a&&(c||"nu"===d||"nn"===d)){if(c)for(g=0;g<b.colModel.length;g++)if(m=b.colModel[g],m.name===a){if(!1===m.odata||m.odataunformat&&(a=e.isFunction(m.odataunformat)?
m.odataunformat(a,c,d):m.odataunformat,!a))return;m.searchrules&&(m.searchrules.integer||m.searchrules.number||m.searchrules.date)?m.searchrules&&m.searchrules.date&&(c=(new Date(c)).toISOString()):c="'"+c+"'";break}switch(d){case "in":case "cn":return"indexof("+a+",tolower("+c+")) gt -1";case "ni":case "nc":return"indexof("+a+",tolower("+c+")) eq -1";case "bw":return"startswith("+a+","+c+") eq true";case "bn":return"startswith("+a+","+c+") eq false";case "ew":return"endswith("+a+","+c+") eq true";
case "en":return"endswith("+a+","+c+") eq false";case "nu":return a+" eq null";case "nn":return a+" ne null";default:return a+" "+d+" "+c}}}function c(b,a){var e,d,g="";if(b.groups&&b.groups.length){for(e=0;e<b.groups.length;e++)g+="("+c(b.groups[e],a)+")",e<b.groups.length-1&&(g+=" "+b.groupOp.toLowerCase()+" ");b.rules&&b.rules.length&&(g+=" "+b.groupOp.toLowerCase()+" ")}if(b.rules.length)for(e=0;e<b.rules.length;e++)d=b.rules[e],(d=f(a,d.field,d.data,d.op))&&(g+=d+" "+b.groupOp.toLowerCase()+
" ");return g=g.trim().replace(/\s(and|or)$/,"").trim()}function d(b,a,d){var k={};if(!a.isQueryApplicable)return k.$format=!a.version||4>a.version?"xml"===a.datatype?"atom":"application/json;odata=fullmetadata":"xml"===a.datatype?"atom":"application/json;odata.metadata=full",k;var k={$top:d.rows,$skip:(parseInt(d.page,10)-1)*b.rowNum},g=b.colModel.filter(function(b){return"json"===b.odataexpand||"subgrid"===b.odataexpand});0<g.length&&(k.$expand=g.reduce(function(b,a){return b+","+a.name},"").substring(1));
"jsonp"===a.datatype&&(k.$callback=a.callback);!a.version||4>a.version?(k.$inlinecount="allpages",k.$format="xml"===a.datatype?"atom":"application/json;odata=fullmetadata"):(k.$count=!0,k.$format="xml"===a.datatype?"atom":"application/json;odata.metadata=full");d.sidx&&(k.$orderby=d.sidx+" "+d.sord);if(!d._search)return k;d.filters?(a=e.parseJSON(d.filters),b=c(a,b),0<b.length&&(k.$filter=b)):k.$filter=f(b,d.searchField,d.searchString,d.searchOper);return k}function h(b,a,d,c){var g=b.data[b._index[c]][b.odataActiveEntitySet];
g&&0<g.length&&(g=g[0]);var m=b.colModel.filter(function(a){return a.name===b.odataActiveEntitySet})[0];c="xml"!==b.datatype?g&&g[b.odataActiveEntitySet+"@odata.navigationLink"]?"{0}/{1}".format(b.odataBaseUrl,g[b.odataActiveEntitySet+"@odata.navigationLink"]):"{0}({1})/{2}".format(b.url,c,b.odataActiveEntitySet):"{0}({1})/{2}".format(b.url,c,b.odataActiveEntitySet);var f={datatype:a.datatype,version:a.version,gencolumns:!1,expandable:a.expandable,odataurl:c,errorfunc:a.errorfunc,annotations:a.annotations,
entitySet:b.odataActiveEntitySet,isQueryApplicable:"complex"!==m.odatatype};e("#"+d).html('<table id="'+d+'_t" class="scroll"></table>');e("#"+d+"_t").jqGrid({colModel:b.odataSubgridCols[b.odataActiveEntitySet],odataSubgridCols:b.odataSubgridCols,loadonce:!0,beforeInitGrid:function(){e(this).jqGrid("odataInit",f)},loadError:function(b,a,g){b=e.jgrid.odataHelper.loadError(b,a,g);b=e("#errdialog").html()+b;e("#errdialog").html(b).dialog("open")}})}function l(b,a){var c;c={datatype:a.datatype,jsonpCallback:a.callback};
var f=function(g,c){return h(b,a,g,c)};e.extend(b,{serializeGridData:function(g){g=d(b,a,g);return this.p.odataPostData=g},ajaxGridOptions:c,mtype:"GET",url:a.odataurl,loadonce:!0},c);for(c=0;c<b.colModel.length;c++)if("subgrid"===b.colModel[c].odataexpand){b.subGrid=!0;b.subGridRowExpanded=f;b.odataActiveEntitySet||(b.odataActiveEntitySet=b.colModel[c].name);break}f={contentType:"application/"+("jsonp"===a.datatype?"json":a.datatype)+";charset=utf-8",datatype:"jsonp"===a.datatype?"json":a.datatype};
b.inlineEditing=e.extend(!0,{beforeSaveRow:function(b,c,e){"edit"===b.extraparam.oper?(b.url=a.odataurl,b.mtype=a.odataverbs.inlineEditingEdit,b.url+="("+c+")"):(b.url=a.odataurl,b.mtype=a.odataverbs.inlineEditingAdd);return!0},serializeSaveData:function(a){return JSON.stringify(a)},ajaxSaveOptions:f},b.inlineEditing||{});e.extend(b.formEditing,{onclickSubmit:function(g,c,e){"add"===e?(g.url=a.odataurl,g.mtype=a.odataverbs.formEditingAdd):"edit"===e&&(g.url=a.odataurl+"("+c[b.id+"_id"]+")",g.mtype=
a.odataverbs.formEditingEdit);return c},ajaxEditOptions:f,serializeEditData:function(a){return JSON.stringify(a)}});e.extend(b.formDeleting,{url:a.odataurl,mtype:"DELETE",serializeDelData:function(a){return""},onclickSubmit:function(a,b){a.url+="("+b+")";return""},ajaxDelOptions:f});f=(f=b.colModel.filter(function(a){return!!a.key})[0])?f.name:b.sortname||"id";"xml"===a.datatype?(a.annotations&&e.extend(!0,b,{loadBeforeSend:function(a){a.setRequestHeader("Prefer",'odata.include-annotations="*"')}}),
e.extend(!0,b,{xmlReader:{root:function(a){a=e(">feed",a).get(0);a.innerHTML=a.innerHTML.replace(/<(\/?)([^:>\s]*:)?([^>]+)>/g,"<$1$3>");var c=e(a).attr("m:context");c&&(b.odataBaseUrl=c.substring(0,c.indexOf("/$metadata")),b.odataEntityType=c.substring(c.indexOf("#")+1).replace("/$entity",""));if(c=e(a).attr("m:type"))b.odataEntityType=c.replace("#","");return a},row:function(a){var b,c=function(){if(!(0<=e(this).attr("href").indexOf("$links"))){var c=e(this).attr("title"),d;0<e(this).html().length?
(d=e(this).find(">inline>feed>entry>content>properties"),0===d.length&&(d=e(this).find(">inline>entry>content>properties")),0<d.length&&(d=d.get(0).childNodes),e(">content>properties "+c,a[b]).remove(),e(">content>properties",a[b]).append(e("<"+c+">").append(d).get(0))):("edit"===e(this).attr("rel")&&0<e(this).attr("href").length&&(c="odata.editLink"),e(">content>properties",a[b]).append(e("<"+c+">").text(e(this).attr("href")).get(0)))}};a=e(">entry",a);for(b=0;b<a.length;b++)e(">link",a[b]).each(c);
return a},cell:function(a){return e(">content>properties",a).get(0).childNodes},records:function(a){return e(">feed>entry",a).length},page:function(a){return Math.ceil((b.odataPostData.$skip+b.rowNum)/b.rowNum)},total:function(a){a=e(">feed>entry",a).length;return Math.ceil((b.odataPostData.$skip+b.rowNum)/b.rowNum)+(0<a?1:0)},repeatitems:!0,userdata:"userdata",id:f}})):(e.extend(!0,b,{jsonReader:{root:function(a){var c=a["@odata.context"];c&&(b.odataBaseUrl=c.substring(0,c.indexOf("/$metadata")),
b.odataEntityType=c.substring(c.indexOf("#")+1).replace("/$entity",""));if(c=a["@odata.type"])b.odataEntityType=c.replace("#","");return a.value||[a]},repeatitems:!0,id:f}}),a.annotations?e.extend(!0,b,{loadBeforeSend:function(a){a.setRequestHeader("Prefer",'odata.include-annotations="*"')},jsonReader:{records:function(b){return b[a.annotationName].records},page:function(b){return b[a.annotationName].page},total:function(b){return b[a.annotationName].total},userdata:function(b){return b[a.annotationName].userdata}}}):
e.extend(!0,b,{jsonReader:{records:function(a){return a["odata.count"]||a["@odata.count"]},page:function(a){var c;a["odata.nextLink"]?c=parseInt(a["odata.nextLink"].split("skip=")[1],10):(c=b.odataPostData.$skip+b.rowNum,a=a["odata.count"]||a["@odata.count"],c>a&&(c=a));return Math.ceil(c/b.rowNum)},total:function(a){return Math.ceil(parseInt(a["odata.count"]||a["@odata.count"],10)/b.rowNum)},userdata:"userdata"}}))}return this.each(function(){var b=this,c=e(b),d=b.p;if(b.grid&&d){var f=e.extend(!0,
{gencolumns:!1,odataurl:d.url,datatype:"json",entitySet:null,annotations:!1,annotationName:"@jqgrid.GridModelAnnotate",isQueryApplicable:!0,odataverbs:{inlineEditingAdd:"POST",inlineEditingEdit:"PATCH",formEditingAdd:"POST",formEditingEdit:"PUT"}},a||{});"jsonp"===f.datatype&&(f.callback="jsonpCallback");if(f.entitySet){if(f.gencolumns){var g=e.extend(!0,{parsecolfunc:null,parsemetadatafunc:null,successfunc:null,errorfunc:null,async:!1,entitySet:null,metadatatype:a.datatype||"xml",metadataurl:(a.odataurl||
d.url)+"/$metadata"},a||{});g.async&&(g.successfunc=function(){b.grid.hDiv&&(b.grid.hDiv.loading=!1);c.trigger("reloadGrid")},b.grid.hDiv&&(b.grid.hDiv.loading=!0));c.jqGrid("odataGenColModel",g)}l(d,f)}else e.isFunction(f.errorfunc)&&f.errorfunc({},"entitySet cannot be empty",0)}})},odataGenColModel:function(a){var f=this[0],c=f.p,d=e(f),h,l,b=e.extend(!0,{parsecolfunc:null,parsemetadatafunc:null,successfunc:null,errorfunc:null,entitySet:null,metadataurl:c.url+"/$metadata",metadatatype:"xml",expandable:"link",
async:!1},a||{});"jsonp"===b.metadatatype&&(b.callback="jsonpCallback");if(b.entitySet)return e.ajax({url:b.metadataurl,type:"GET",dataType:b.metadatatype,jsonpCallback:b.callback,async:b.async,cache:!1}).done(function(a,f,k){var g=0,m=0,t=0;if("json"===b.metadatatype||"jsonp"===b.metadatatype)a=e.jgrid.odataHelper.resolveJsonReferences(a);h=d.triggerHandler("jqGridODataParseMetadata",a);!h&&e.isFunction(b.parsemetadatafunc)&&(h=b.parsemetadatafunc(a,f,k));if(!h&&(h=d.jqGrid("parseMetadata",a,b.metadatatype))&&
(l=d.triggerHandler("jqGridODataParseColumns",[b,h]),!l&&e.isFunction(b.parsecolfunc)&&(l=b.parsecolfunc(b,h)),!l))for(g in l={},h)h.hasOwnProperty(g)&&g&&(l[g]=d.jqGrid("parseColumns",h[g],b.expandable));if(l){for(t in l)if(l.hasOwnProperty(t)&&t)for(g=0;g<c.colModel.length;g++)for(m=0;m<l[t].length;m++)if(l[t][m].name===c.colModel[g].name){e.extend(!0,l[t][m],c.colModel[g]);break}c.colModel=l[b.entitySet];c.odataSubgridCols=l;e.isFunction(b.successfunc)&&b.successfunc()}else e.isFunction(b.errorfunc)&&
b.errorfunc({data:a,status:f,xhr:k},"parse $metadata error")}).fail(function(a,c,d){if(e.isFunction(b.errorfunc)){var f=e.jgrid.odataHelper.loadError(a,c,d);b.errorfunc({xhr:a,error:c,code:d},f)}}),l;e.isFunction(b.errorfunc)&&b.errorfunc({},"entitySet cannot be empty",0)}})})(jQuery);
