(function(e){String.prototype.format||(String.prototype.format=function(){var a=arguments;return this.replace(/\{\{|\}\}|\{(\d+)\}/g,function(e,c){return"{{"===e?"{":"}}"===e?"}":a[c]})});e.jgrid.odataHelper={resolveJsonReferences:function(a,e){function c(b,a,m){if("object"!==typeof b||!b)return b;if("[object Array]"===Object.prototype.toString.call(b)){for(d=0;d<b.length;d++){if("object"!==typeof b[d]||!b[d])return b[d];b[d]=b[d].$ref?c(b[d],d,b):c(b[d],a,b)}return b}if(b.$ref){g=b.$ref;if(k[g])return k[g];
e.push([m,a,g])}else{if(b.$id){a=b.$id;delete b.$id;if(b.$values)b=b.$values.map(c);else for(var h in b)b.hasOwnProperty(h)&&(b[h]=c(b[h],h,b));k[a]=b}return b}}var d,g,k={};e=e||[];"string"===typeof a&&(a=JSON.parse(a));a=c(a);for(d=0;d<e.length;d++)g=e[d],g[0][g[1]]=k[g[2]];return a},convertXmlToJson:function(a){var f={},c,d,g,k;if(!a)return null;if(1===a.nodeType){if(0<a.attributes.length)for(f["@attributes"]={},c=0;c<a.attributes.length;c++)d=a.attributes.item(c),f["@attributes"][d.nodeName]=
d.nodeValue}else 3===a.nodeType?f=a.nodeValue:a.nodeType||(f=a);if(a.hasChildNodes&&a.hasChildNodes())for(c=0;c<a.childNodes.length;c++){d=a.childNodes.item(c);if(3===d.nodeType)return d.nodeValue;g=d.nodeName;void 0===f[g]?f[g]=e.jgrid.odataHelper.convertXmlToJson(d):(void 0===f[g].push&&(k=f[g],f[g]=[],f[g].push(k)),f[g].push(e.jgrid.odataHelper.convertXmlToJson(d)))}return e.isEmptyObject(f)?null:f},parseMetadata:function(a,f){function c(a){var k,b,c,d,h,l,f,n,q,p,r={},v={};l=e("Schema",a).attr("Namespace")+
".";e("EntityContainer EntitySet",a).each(function(b,a){v[e(a).attr("EntityType")]=e(a).attr("Name")});e("EntityType, ComplexType",a).each(function(){b=e(this).find("Property,NavigationProperty");d=(c=e("Key PropertyRef",this))&&0<c.length?c.first().attr("Name"):"";q=e(this).attr("Name");b&&(k=[],b.each(function(b,c){p={};e.each(c.attributes,function(){p[this.name]=this.value});h=p.Name===d;n="NavigationProperty"===c.tagName;f="Property"===c.tagName&&0<e('ComplexType[Name="'+p.Name+'"]',a).length;
k.push(e.extend({iskey:h,isComplex:f,isNavigation:n},p))}),r[v[l+q]]=k,r[q]=k)});return r}function d(a){var k,b,c,e,h,l,d,f,q,p,r={};for(f=0;f<a.SchemaElements.length;f++)if(b=a.SchemaElements[f].DeclaredProperties,a.SchemaElements[f].NavigationProperties&&(b=b.concat(a.SchemaElements[f].NavigationProperties)),c=(k=a.SchemaElements[f].DeclaredKey)&&0<k.length?k[0].Name:"",p=a.SchemaElements[f].Namespace,e=a.SchemaElements[f].Name,b){k=[];for(f=0;f<b.length;f++)d=b[f].Name===c,l=b[f].Type.IsNullable,
h=b[f].Type.Definition.Namespace+"."+b[f].Type.Definition.Name,q=!!p&&0<=h.indexOf(p),k.push({Name:b[f].Name,Type:h,Nullable:l,iskey:d,isComplex:q,isNavigation:!1});r[e]=k}return r}return"xml"===f?c(a):d(a)},loadError:function(a,f,c){var d=a.status,g=c;if(!a.responseJSON)if(a.responseXML)a.responseText=a.responseText.replace(/<(\/?)([^:>\s]*:)?([^>]+)>/g,"<$1$3>"),a.responseXML=e.parseXML(a.responseText),a.responseJSON=e.jgrid.odataHelper.convertXmlToJson(a.responseXML);else if(a.responseText)try{a.responseJSON=
e.parseJSON(a.responseText)}catch(k){}if(a.responseJSON){if(a=a.responseJSON["@odata.error"]||a.responseJSON["odata.error"]||a.responseJSON.error)a.innererror?a.innererror.internalexception?(f=a.innererror.internalexception.message,g=a.innererror.internalexception.stacktrace||""):(f=a.innererror.message,g=a.innererror.stacktrace||""):(f=a.message.value||a.message,g=a.stacktrace||"")}else c&&e.isPlainObject(c)&&(f=c.message,g=c.stack,d=c.code);return"<div>Status/error code: "+d+"</div><div>Message: "+
f+'</div><div style="font-size: 0.8em;">'+g+"</div><br/>"}};e.jgrid.cmTemplate.odataComplexType={editable:!1,formatter:function(a,f,c){return e(this).jqGrid("odataJson",a,f,c)}};e.jgrid.cmTemplate.odataNavigationProperty={editable:!1,formatter:function(a,f,c){if(!f.colModel.odata.expand||"link"===f.colModel.odata.expand)return e(this).jqGrid("odataLink",a,f,c);if("json"===f.colModel.odata.expand)return e(this).jqGrid("odataJson",a,f,c);if("subgrid"===f.colModel.odata.expand)return e(this).jqGrid("odataSubgrid",
a,f,c)}};e.jgrid.cmTemplate["Edm.GeographyPoint"]={editable:!1,formatter:function(a,f,c){a||"xml"!==this.p.datatype||(a=e(c).filter(function(){return this.localName.toLowerCase()===f.colModel.name.toLowerCase()}),a=e.jgrid.odataHelper.convertXmlToJson(a[0]));return a.crs&&a.coordinates?"<div>{0}</div><div>[{1},{2}]</div>".format(a.crs.properties.name,a.coordinates[0],a.coordinates[1]):"<div>{0}</div>".format(a)}};e.jgrid.extend({odataLink:function(a,f,c){var d=this[0].p;if("xml"!==d.datatype){if(c[f.colModel.name+
"@odata.navigationLink"])return a=c[f.colModel.name+"@odata.navigationLink"],f='<a href="{0}/{1}" target="_self">{2}</a>'.format(d.odata.baseUrl,a,f.colModel.name);a=c[d.jsonReader.id]}else a=function(a){return e(c).filter(function(){return this.localName&&this.localName.toLowerCase()===a}).text()}(d.xmlReader.id.toLowerCase());return f=d.odata.iscollection?'<a href="{0}({1})/{2}" target="_self">{2}</a>'.format(d.url,a,f.colModel.name):'<a href="{0}/{1}" target="_self">{1}</a>'.format(d.url,f.colModel.name)},
odataJson:function(a,f,c){var d,g={};"xml"===this[0].p.datatype&&(a=e(c).filter(function(){return this.localName.toLowerCase()===f.colModel.name.toLowerCase()}),a=e.jgrid.odataHelper.convertXmlToJson(a[0]));for(d in a)a.hasOwnProperty(d)&&d&&0>d.indexOf("@odata.")&&0>d.indexOf("@attributes")&&(g[d]=a[d]);return JSON.stringify(g,null,1)},odataSubgrid:function(a,f,c){var d,g=this[0].p;a="xml"!==g.datatype?c[g.jsonReader.id]:function(a){return e(c).filter(function(){return this.localName&&this.localName.toLowerCase()===
a}).text()}(g.xmlReader.id.toLowerCase());for(d in g._index)if(g._index.hasOwnProperty(d)&&d&&a===g._index[d].toString()){a=d;break}return f='<a style="cursor:pointer" data-id="{0}" onclick=\'$("#{2}").jqGrid("setGridParam", { odata: {activeEntitySet: "{1}" } });$("#{2}").jqGrid("expandSubGridRow", "{0}");return false;\'>{1}</a>'.format(a,f.colModel.name,f.gid)},parseColumns:function(a,f){for(var c=0,d,g,k,b,u,m=[],h,c=0;c<a.length;c++)d=0<="Edm.Int16,Edm.Int32,Edm.Int64".indexOf(a[c].Type),g=0<=
"Edm.Decimal,Edm.Double,Edm.Single".indexOf(a[c].Type),b=0<="Edm.Byte,Edm.SByte".indexOf(a[c].Type),k=a[c].Type&&0<=a[c].Type.indexOf("Edm.")&&(0<=a[c].Type.indexOf("Date")||0<=a[c].Type.indexOf("Time")),u=e.jgrid.cmTemplate[a[c].Type]?a[c].Type:a[c].isComplex?"odataComplexType":a[c].isNavigation?"odataNavigationProperty":d?"integerStr":g?"numberStr":b?"booleanCheckbox":"text",h={integer:d,number:g,date:k,required:!a[c].Nullable||"false"===a[c].Nullable},d=d?"integer":g?"number":k?"datetime":b?"checkbox":
"text",g=a[c].isNavigation||a[c].isComplex?'<span class="ui-icon ui-icon-arrowreturn-1-s" style="display:inline-block;vertical-align:middle;"></span>'+a[c].Name:a[c].Name,m.push(e.extend({label:g,name:a[c].Name,index:a[c].Name,editable:!a[c].isNavigation&&!a[c].iskey,searchrules:h,editrules:h,searchtype:d,inputtype:d,edittype:d,key:a[c].iskey,odata:{expand:a[c].isNavigation?f:a[c].isComplex?"json":null,isnavigation:a[c].isNavigation,iscomplex:a[c].isComplex,iscollection:0<=a[c].Type.indexOf("Collection")}},
e.jgrid.cmTemplate[u]));return m},odataInit:function(a){function f(a,b,c,f){var h,l;if(b&&(c||"nu"===f||"nn"===f)){if(c)for(h=0;h<a.colModel.length;h++)if(l=a.colModel[h],l.name===b){if(l.odata.nosearch||l.odata.unformat&&(b=e.isFunction(l.odata.unformat)?l.odata.unformat(b,c,f):l.odata.unformat,!b))return;l.searchrules&&(l.searchrules.integer||l.searchrules.number||l.searchrules.date)?l.searchrules&&l.searchrules.date&&(c=(new Date(c)).toISOString()):c="'"+c+"'";break}switch(f){case "in":case "cn":return"indexof("+
b+",tolower("+c+")) gt -1";case "ni":case "nc":return"indexof("+b+",tolower("+c+")) eq -1";case "bw":return"startswith("+b+","+c+") eq true";case "bn":return"startswith("+b+","+c+") eq false";case "ew":return"endswith("+b+","+c+") eq true";case "en":return"endswith("+b+","+c+") eq false";case "nu":return b+" eq null";case "nn":return b+" ne null";default:return b+" "+f+" "+c}}}function c(a,b){var e,d,h="";if(a.groups&&a.groups.length){for(e=0;e<a.groups.length;e++)h+="("+c(a.groups[e],b)+")",e<a.groups.length-
1&&(h+=" "+a.groupOp.toLowerCase()+" ");a.rules&&a.rules.length&&(h+=" "+a.groupOp.toLowerCase()+" ")}if(a.rules.length)for(e=0;e<a.rules.length;e++)d=a.rules[e],(d=f(b,d.field,d.data,d.op))&&(h+=d+" "+a.groupOp.toLowerCase()+" ");return h=h.trim().replace(/\s(and|or)$/,"").trim()}function d(a,b,c,f){var h=a.colModel.filter(function(b){return b.name===a.odata.activeEntitySet})[0];f=a._index[f];f=a.odata.iscollection?"{0}({1})/{2}".format(a.url,f,a.odata.activeEntitySet):"{0}/{1}".format(a.url,a.odata.activeEntitySet);
var l={datatype:b.datatype,version:b.version,gencolumns:!1,expandable:b.expandable,odataurl:f,errorfunc:b.errorfunc,annotations:b.annotations,entitySet:a.odata.activeEntitySet};e("#"+c).html('<table id="'+c+'_t" class="scroll"></table>');e("#"+c+"_t").jqGrid({colModel:a.odata.subgridCols[a.odata.activeEntitySet],odata:e.extend({},a.odata,h.odata),loadonce:!0,beforeInitGrid:function(){e(this).jqGrid("odataInit",l)},loadError:function(a,b,h){a=e.jgrid.odataHelper.loadError(a,b,h);a=e("#errdialog").html()+
a;e("#errdialog").html(a).dialog("open")}})}function g(a,b){var g;g={datatype:b.datatype,jsonpCallback:b.callback};var m=function(h,c){return d(a,b,h,c)};a.odata||(a.odata={iscollection:!0});e.extend(a,{serializeGridData:function(h){var d=h;h={};a.odata.iscollection?(h={$top:d.rows,$skip:(parseInt(d.page,10)-1)*a.rowNum},"jsonp"===b.datatype&&(h.$callback=b.callback),!b.version||4>b.version?(h.$inlinecount="allpages",h.$format="xml"===b.datatype?"atom":"application/json;odata=fullmetadata"):(h.$count=
!0,h.$format="xml"===b.datatype?"atom":"application/json;odata.metadata=full"),d.sidx&&(h.$orderby=d.sidx+" "+d.sord),d._search&&(d.filters?(d=e.parseJSON(d.filters),d=c(d,a),0<d.length&&(h.$filter=d)):h.$filter=f(a,d.searchField,d.searchString,d.searchOper))):h.$format=!b.version||4>b.version?"xml"===b.datatype?"atom":"application/json;odata=fullmetadata":"xml"===b.datatype?"atom":"application/json;odata.metadata=full";return this.p.odata.postData=h},ajaxGridOptions:g,mtype:"GET",url:b.odataurl,
loadonce:!0},g);for(g=0;g<a.colModel.length;g++)if(a.colModel[g].odata&&"subgrid"===a.colModel[g].odata.expand){a.subGrid=!0;a.subGridRowExpanded=m;a.odata.activeEntitySet=a.colModel[g].name;break}m={contentType:"application/"+("jsonp"===b.datatype?"json":b.datatype)+";charset=utf-8",datatype:"jsonp"===b.datatype?"json":b.datatype};a.inlineEditing=e.extend(!0,{beforeSaveRow:function(a,c){"edit"===a.extraparam.oper?(a.url=b.odataurl,a.mtype=b.odataverbs.inlineEditingEdit,a.url+="("+c+")"):(a.url=b.odataurl,
a.mtype=b.odataverbs.inlineEditingAdd);return!0},serializeSaveData:function(a){return JSON.stringify(a)},ajaxSaveOptions:m},a.inlineEditing||{});e.extend(a.formEditing,{onclickSubmit:function(h,c,e){"add"===e?(h.url=b.odataurl,h.mtype=b.odataverbs.formEditingAdd):"edit"===e&&(h.url=b.odataurl+"("+c[a.id+"_id"]+")",h.mtype=b.odataverbs.formEditingEdit);return c},ajaxEditOptions:m,serializeEditData:function(a){return JSON.stringify(a)}});e.extend(a.formDeleting,{url:b.odataurl,mtype:"DELETE",serializeDelData:function(){return""},
onclickSubmit:function(a,b){a.url+="("+b+")";return""},ajaxDelOptions:m});m=(m=a.colModel.filter(function(a){return!!a.key})[0])?m.name:a.sortname||"id";"xml"===b.datatype?(b.annotations&&e.extend(!0,a,{loadBeforeSend:function(a){a.setRequestHeader("Prefer",'odata.include-annotations="*"')}}),e.extend(!0,a,{xmlReader:{root:function(b){b=b.childNodes[0];b.innerHTML=b.innerHTML.replace(/<(\/?)([^:>\s]*:)?([^>]+)>/g,"<$1$3>");var c=e(b).attr("m:context");c&&(a.odata.baseUrl=c.substring(0,c.indexOf("/$metadata")),
a.odata.entityType=c.substring(c.indexOf("#")+1).replace("/$entity",""));if(c=e(b).attr("m:type"))a.odata.entityType=c.replace("#","");return b},row:function(a){return a="entry"===a.localName?[a]:e(">entry",a)},cell:function(a){return e(">content>properties",a).get(0).childNodes},records:function(a){return e(">feed>entry",a).length},page:function(){return Math.ceil((a.odata.postData.$skip+a.rowNum)/a.rowNum)},total:function(b){b=e(">feed>entry",b).length;return Math.ceil((a.odata.postData.$skip+a.rowNum)/
a.rowNum)+(0<b?1:0)},repeatitems:!0,userdata:"userdata",id:m}})):(e.extend(!0,a,{jsonReader:{root:function(b){var c=b["@odata.context"];c&&(a.odata.baseUrl=c.substring(0,c.indexOf("/$metadata")),a.odata.entityType=c.substring(c.indexOf("#")+1).replace("/$entity",""));if(c=b["@odata.type"])a.odata.entityType=c.replace("#","");return b.value||[b]},repeatitems:!0,id:m}}),b.annotations?e.extend(!0,a,{loadBeforeSend:function(a){a.setRequestHeader("Prefer",'odata.include-annotations="*"')},jsonReader:{records:function(a){return a[b.annotationName].records},
page:function(a){return a[b.annotationName].page},total:function(a){return a[b.annotationName].total},userdata:function(a){return a[b.annotationName].userdata}}}):e.extend(!0,a,{jsonReader:{records:function(a){return a["odata.count"]||a["@odata.count"]},page:function(b){var c;b["odata.nextLink"]?c=parseInt(b["odata.nextLink"].split("skip=")[1],10):(c=a.odata.postData.$skip+a.rowNum,b=b["odata.count"]||b["@odata.count"],c>b&&(c=b));return Math.ceil(c/a.rowNum)},total:function(b){return Math.ceil(parseInt(b["odata.count"]||
b["@odata.count"],10)/a.rowNum)},userdata:"userdata"}}))}return this.each(function(){var c=this,b=e(c),d=c.p;if(c.grid&&d){var f=e.extend(!0,{gencolumns:!1,odataurl:d.url,datatype:"json",entitySet:null,annotations:!1,annotationName:"@jqgrid.GridModelAnnotate",odataverbs:{inlineEditingAdd:"POST",inlineEditingEdit:"PATCH",formEditingAdd:"POST",formEditingEdit:"PUT"}},a||{});"jsonp"===f.datatype&&(f.callback="jsonpCallback");if(f.entitySet){if(f.gencolumns){var h=e.extend(!0,{parsecolfunc:null,parsemetadatafunc:null,
successfunc:null,errorfunc:null,async:!1,entitySet:null,metadatatype:a.datatype||"xml",metadataurl:(a.odataurl||d.url)+"/$metadata"},a||{});h.async&&(h.successfunc=function(){c.grid.hDiv&&(c.grid.hDiv.loading=!1);b.trigger("reloadGrid")},c.grid.hDiv&&(c.grid.hDiv.loading=!0));b.jqGrid("odataGenColModel",h)}g(d,f)}else e.isFunction(f.errorfunc)&&f.errorfunc({},"entitySet cannot be empty",0)}})},odataGenColModel:function(a){var f=this[0],c=f.p,d=e(f),g,k,b=e.extend(!0,{parsecolfunc:null,parsemetadatafunc:null,
successfunc:null,errorfunc:null,entitySet:null,metadataurl:c.url+"/$metadata",metadatatype:"xml",expandable:"link",async:!1},a||{});"jsonp"===b.metadatatype&&(b.callback="jsonpCallback");if(b.entitySet)return e.ajax({url:b.metadataurl,type:"GET",dataType:b.metadatatype,jsonpCallback:b.callback,async:b.async,cache:!1}).done(function(a,f,h){var l=0,t=0,n=0;if("json"===b.metadatatype||"jsonp"===b.metadatatype)a=e.jgrid.odataHelper.resolveJsonReferences(a);g=d.triggerHandler("jqGridODataParseMetadata",
a);!g&&e.isFunction(b.parsemetadatafunc)&&(g=b.parsemetadatafunc(a,f,h));if(!g&&(g=e.jgrid.odataHelper.parseMetadata(a,b.metadatatype))&&(k=d.triggerHandler("jqGridODataParseColumns",[b,g]),!k&&e.isFunction(b.parsecolfunc)&&(k=b.parsecolfunc(b,g)),!k))for(l in k={},g)g.hasOwnProperty(l)&&l&&(k[l]=d.jqGrid("parseColumns",g[l],b.expandable));if(k){for(n in k)if(k.hasOwnProperty(n)&&n)for(l=0;l<c.colModel.length;l++)for(t=0;t<k[n].length;t++)if(k[n][t].name===c.colModel[l].name){e.extend(!0,k[n][t],
c.colModel[l]);break}c.colModel=k[b.entitySet];c.odata||(c.odata={iscollection:!0});c.odata.subgridCols=k;e.isFunction(b.successfunc)&&b.successfunc()}else e.isFunction(b.errorfunc)&&b.errorfunc({data:a,status:f,xhr:h},"parse $metadata error")}).fail(function(a,c,d){if(e.isFunction(b.errorfunc)){var f=e.jgrid.odataHelper.loadError(a,c,d);b.errorfunc({xhr:a,error:c,code:d},f)}}),k;e.isFunction(b.errorfunc)&&b.errorfunc({},"entitySet cannot be empty",0)}})})(jQuery);
