(function(a){a.jgrid.extend({searchGrid:function(b){b=a.extend({recreateFilter:!1,drag:!0,sField:"searchField",sValue:"searchString",sOper:"searchOper",sFilter:"filters",loadDefaults:!0,beforeShowSearch:null,afterShowSearch:null,onInitializeSearch:null,closeAfterSearch:!1,closeAfterReset:!1,closeOnEscape:!1,multipleSearch:!1,cloneSearchRowOnAdd:!0,sopt:null,stringResult:void 0,onClose:null,useDataProxy:!1,overlay:!0},a.jgrid.search,b||{});return this.each(function(){function p(b,d){var c=b.p.postData[d.sFilter];
"string"==typeof c&&(c=a.jgrid.parse(c));if(c&&(c.groupOp&&b.SearchFilter.setGroupOp(c.groupOp),c.rules)){var h,e=0,f=c.rules.length;for(h=!1;e<f;e++)h=c.rules[e],void 0!==h.field&&void 0!==h.op&&void 0!==h.data&&(h=b.SearchFilter.setFilter({sfref:b.SearchFilter.$.find(".sf:last"),filter:a.extend({},h)}))&&b.SearchFilter.add()}}function d(c){if(b.onClose){var d=b.onClose(c);if("boolean"==typeof d&&!d)return}c.hide();!0===b.overlay&&a(".jqgrid-overlay:first","#gbox_"+l.p.id).hide()}function g(){var c=
a(".ui-searchFilter").length;if(1<c){var d=a("#"+e).css("zIndex");a("#"+e).css({zIndex:parseInt(d,10)+c})}a("#"+e).show();!0===b.overlay&&a(".jqgrid-overlay:first","#gbox_"+l.p.id).show();try{a(":input:visible","#"+e)[0].focus()}catch(h){}}function t(c){var h=void 0!==c,f=a("#"+l.p.id),r={};!1===b.multipleSearch?(r[b.sField]=c.rules[0].field,r[b.sValue]=c.rules[0].data,r[b.sOper]=c.rules[0].op,r.hasOwnProperty(b.sFilter)&&delete r[b.sFilter]):(r[b.sFilter]=c,a.each([b.sField,b.sValue,b.sOper],function(a,
c){r.hasOwnProperty(c)&&delete r[c]}));f[0].p.search=h;a.extend(f[0].p.postData,r);f.trigger("reloadGrid",[{page:1}]);b.closeAfterSearch&&d(a("#"+e))}function q(c){c=c&&c.hasOwnProperty("reload")?c.reload:!0;var h=a("#"+l.p.id),f={};h[0].p.search=!1;!1===b.multipleSearch?f[b.sField]=f[b.sValue]=f[b.sOper]="":f[b.sFilter]="";a.extend(h[0].p.postData,f);c&&h.trigger("reloadGrid",[{page:1}]);b.closeAfterReset&&d(a("#"+e))}var l=this;if(l.grid){var e="fbox_"+l.p.id,n=!0;if(a.fn.searchFilter)if(!0===b.recreateFilter&&
a("#"+e).remove(),null!=a("#"+e).html())a.isFunction(b.beforeShowSearch)&&(n=b.beforeShowSearch(a("#"+e)),"undefined"==typeof n&&(n=!0)),!1!==n&&(g(),a.isFunction(b.afterShowSearch)&&b.afterShowSearch(a("#"+e)));else{var m=[],x=a("#"+l.p.id).jqGrid("getGridParam","colNames"),r=a("#"+l.p.id).jqGrid("getGridParam","colModel"),h="eq ne lt le gt ge bw bn in ni ew en cn nc".split(" "),c,f,w,u=[];if(null!==b.sopt)for(c=w=0;c<b.sopt.length;c++)-1!=(f=a.inArray(b.sopt[c],h))&&(u[w]={op:b.sopt[c],text:b.odata[f].text},
w++);else for(c=0;c<h.length;c++)u[c]={op:h[c],text:b.odata[c].text};a.each(r,function(d,e){var r="undefined"===typeof e.search?!0:e.search,l=!0===e.hidden,k=a.extend({},{text:x[d],itemval:e.index||e.name},this.searchoptions),n=!0===k.searchhidden;if("undefined"!==typeof k.sopt&&(w=0,k.ops=[],0<k.sopt.length))for(c=0;c<k.sopt.length;c++)-1!=(f=a.inArray(k.sopt[c],h))&&(k.ops[w]={op:k.sopt[c],text:b.odata[f].text},w++);"undefined"===typeof this.stype&&(this.stype="text");if("select"==this.stype&&void 0===
k.dataUrl){var g;k.value?g=k.value:this.editoptions&&(g=this.editoptions.value);if(g)if(k.dataValues=[],"string"===typeof g){g=g.split(";");var u;for(c=0;c<g.length;c++)u=g[c].split(":"),k.dataValues[c]={value:u[0],text:u[1]}}else if("object"===typeof g)for(u in c=0,g)g.hasOwnProperty(u)&&(k.dataValues[c]={value:u,text:g[u]},c++)}(n&&r||r&&!l)&&m.push(k)});if(0<m.length){a("<div id='"+e+"' role='dialog' tabindex='-1'></div>").insertBefore("#gview_"+l.p.id);void 0===b.stringResult&&(b.stringResult=
b.multipleSearch);l.SearchFilter=a("#"+e).searchFilter(m,{groupOps:b.groupOps,operators:u,onClose:d,resetText:b.Reset,searchText:b.Find,windowTitle:b.caption,rulesText:b.rulesText,matchText:b.matchText,onSearch:t,onReset:q,stringResult:b.stringResult,ajaxSelectOptions:a.extend({},a.jgrid.ajaxOptions,l.p.ajaxSelectOptions||{}),clone:b.cloneSearchRowOnAdd});a(".ui-widget-overlay","#"+e).remove();"rtl"==l.p.direction&&a(".ui-closer","#"+e).css("float","left");if(!0===b.drag)if(a("#"+e+" table thead tr:first td:first").css("cursor",
"move"),jQuery.fn.jqDrag)a("#"+e).jqDrag(a("#"+e+" table thead tr:first td:first"));else try{a("#"+e).draggable({handle:a("#"+e+" table thead tr:first td:first")})}catch(k){}!1===b.multipleSearch&&(a(".ui-del, .ui-add, .ui-del, .ui-add-last, .matchText, .rulesText","#"+e).hide(),a("select[name='groupOp']","#"+e).hide());!0===b.multipleSearch&&!0===b.loadDefaults&&p(l,b);if(a.isFunction(b.onInitializeSearch))b.onInitializeSearch(a("#"+e));a.isFunction(b.beforeShowSearch)&&(n=b.beforeShowSearch(a("#"+
e)),"undefined"==typeof n&&(n=!0));!1!==n&&(g(),a.isFunction(b.afterShowSearch)&&b.afterShowSearch(a("#"+e)),!0===b.closeOnEscape&&a("#"+e).keydown(function(c){27==c.which&&d(a("#"+e));13==c.which&&a(".ui-search",this).click()}))}}}})},updateGridRows:function(b,p,d){var g,t=!1,q;this.each(function(){var l=this,e,n,m,x;if(!l.grid)return!1;p||(p="id");b&&0<b.length&&a(b).each(function(b){m=this;if(n=l.rows.namedItem(m[p])){x=m[p];if(!0===d&&!0===l.p.jsonReader.repeatitems){l.p.jsonReader.cell&&(m=m[l.p.jsonReader.cell]);
for(b=0;b<m.length;b++)e=l.formatter(x,m[b],b,m,"edit"),q=l.p.colModel[b].title?{title:a.jgrid.stripHtml(e)}:{},!0===l.p.treeGrid&&g==l.p.ExpandColumn?a("td:eq("+b+") > span:first",n).html(e).attr(q):a("td:eq("+b+")",n).html(e).attr(q);return t=!0}a(l.p.colModel).each(function(b){g=!0===d?this.jsonmap||this.name:this.name;void 0!==m[g]&&(e=l.formatter(x,m[g],b,m,"edit"),q=this.title?{title:a.jgrid.stripHtml(e)}:{},!0===l.p.treeGrid&&g==l.p.ExpandColumn?a("td:eq("+b+") > span:first",n).html(e).attr(q):
a("td:eq("+b+")",n).html(e).attr(q),t=!0)})}})});return t},filterGrid:function(b,p){p=a.extend({gridModel:!1,gridNames:!1,gridToolbar:!1,filterModel:[],formtype:"horizontal",autosearch:!0,formclass:"filterform",tableclass:"filtertable",buttonclass:"filterbutton",searchButton:"Search",clearButton:"Clear",enableSearch:!1,enableClear:!1,beforeSearch:null,afterSearch:null,beforeClear:null,afterClear:null,url:"",marksearched:!0},p||{});return this.each(function(){var d=this;this.p=p;if(0===this.p.filterModel.length&&
!1===this.p.gridModel)alert("No filter is set");else if(b){this.p.gridid=-1!=b.indexOf("#")?b:"#"+b;var g=a(this.p.gridid).jqGrid("getGridParam","colModel");if(g){if(!0===this.p.gridModel){var t=a(this.p.gridid)[0],q;a.each(g,function(a,b){var h=[];this.search=!1===this.search?!1:!0;q=this.editrules&&!0===this.editrules.searchhidden?!0:!0===this.hidden?!1:!0;!0===this.search&&!0===q&&(h.label=!0===d.p.gridNames?t.p.colNames[a]:"",h.name=this.name,h.index=this.index||this.name,h.stype=this.edittype||
"text","select"!=h.stype&&(h.stype="text"),h.defval=this.defval||"",h.surl=this.surl||"",h.sopt=this.editoptions||{},h.width=this.width,d.p.filterModel.push(h))})}else a.each(d.p.filterModel,function(a,b){for(var d=0;d<g.length;d++)if(this.name==g[d].name){this.index=g[d].index||this.name;break}this.index||(this.index=this.name)});var l=function(){var b={},e=0,h,c=a(d.p.gridid)[0],f;c.p.searchdata={};a.isFunction(d.p.beforeSearch)&&d.p.beforeSearch();a.each(d.p.filterModel,function(k,l){f=this.index;
if("select"===this.stype)if(h=a("select[name="+f+"]",d).val())b[f]=h,d.p.marksearched&&a("#jqgh_"+this.name,c.grid.hDiv).addClass("dirty-cell"),e++;else{d.p.marksearched&&a("#jqgh_"+this.name,c.grid.hDiv).removeClass("dirty-cell");try{delete c.p.postData[this.index]}catch(g){}}else if(h=a("input[name="+f+"]",d).val())b[f]=h,d.p.marksearched&&a("#jqgh_"+this.name,c.grid.hDiv).addClass("dirty-cell"),e++;else{d.p.marksearched&&a("#jqgh_"+this.name,c.grid.hDiv).removeClass("dirty-cell");try{delete c.p.postData[this.index]}catch(n){}}});
var l=0<e?!0:!1;a.extend(c.p.postData,b);var g;d.p.url&&(g=a(c).jqGrid("getGridParam","url"),a(c).jqGrid("setGridParam",{url:d.p.url}));a(c).jqGrid("setGridParam",{search:l}).trigger("reloadGrid",[{page:1}]);g&&a(c).jqGrid("setGridParam",{url:g});a.isFunction(d.p.afterSearch)&&d.p.afterSearch()},e=function(){var b={},e,h=0,c=a(d.p.gridid)[0],f;a.isFunction(d.p.beforeClear)&&d.p.beforeClear();a.each(d.p.filterModel,function(k,l){f=this.index;e=this.defval?this.defval:"";this.stype||(this.stype="text");
switch(this.stype){case "select":var g;a("select[name="+f+"] option",d).each(function(b){0===b&&(this.selected=!0);if(a(this).text()==e)return this.selected=!0,g=a(this).val(),!1});if(g)b[f]=g,d.p.marksearched&&a("#jqgh_"+this.name,c.grid.hDiv).addClass("dirty-cell"),h++;else{d.p.marksearched&&a("#jqgh_"+this.name,c.grid.hDiv).removeClass("dirty-cell");try{delete c.p.postData[this.index]}catch(n){}}break;case "text":if(a("input[name="+f+"]",d).val(e),e)b[f]=e,d.p.marksearched&&a("#jqgh_"+this.name,
c.grid.hDiv).addClass("dirty-cell"),h++;else{d.p.marksearched&&a("#jqgh_"+this.name,c.grid.hDiv).removeClass("dirty-cell");try{delete c.p.postData[this.index]}catch(m){}}}});var l=0<h?!0:!1;a.extend(c.p.postData,b);var g;d.p.url&&(g=a(c).jqGrid("getGridParam","url"),a(c).jqGrid("setGridParam",{url:d.p.url}));a(c).jqGrid("setGridParam",{search:l}).trigger("reloadGrid",[{page:1}]);g&&a(c).jqGrid("setGridParam",{url:g});a.isFunction(d.p.afterClear)&&d.p.afterClear()},n,m=a("<form name='SearchForm' style=display:inline;' class='"+
this.p.formclass+"'></form>");n=a("<table class='"+this.p.tableclass+"' cellspacing='0' cellpadding='0' border='0'><tbody></tbody></table>");a(m).append(n);(function(){var b=document.createElement("tr"),g,h,c,f;"horizontal"==d.p.formtype&&a(n).append(b);a.each(d.p.filterModel,function(e,h){c=document.createElement("td");a(c).append("<label for='"+this.name+"'>"+this.label+"</label>");f=document.createElement("td");var k=this;this.stype||(this.stype="text");switch(this.stype){case "select":if(this.surl)a(f).load(this.surl,
function(){k.defval&&a("select",this).val(k.defval);a("select",this).attr({name:k.index||k.name,id:"sg_"+k.name});k.sopt&&a("select",this).attr(k.sopt);!0===d.p.gridToolbar&&k.width&&a("select",this).width(k.width);!0===d.p.autosearch&&a("select",this).change(function(a){l();return!1})});else if(k.sopt.value){var m=k.sopt.value,q=document.createElement("select");a(q).attr({name:k.index||k.name,id:"sg_"+k.name}).attr(k.sopt);var p,v;if("string"===typeof m)for(var m=m.split(";"),t=0;t<m.length;t++)p=
m[t].split(":"),v=document.createElement("option"),v.value=p[0],v.innerHTML=p[1],p[1]==k.defval&&(v.selected="selected"),q.appendChild(v);else if("object"===typeof m)for(p in m)m.hasOwnProperty(p)&&(e++,v=document.createElement("option"),v.value=p,v.innerHTML=m[p],m[p]==k.defval&&(v.selected="selected"),q.appendChild(v));!0===d.p.gridToolbar&&k.width&&a(q).width(k.width);a(f).append(q);!0===d.p.autosearch&&a(q).change(function(a){l();return!1})}break;case "text":q=this.defval?this.defval:"",a(f).append("<input type='text' name='"+
(this.index||this.name)+"' id='sg_"+this.name+"' value='"+q+"'/>"),k.sopt&&a("input",f).attr(k.sopt),!0===d.p.gridToolbar&&k.width&&(a.browser.msie?a("input",f).width(k.width-4):a("input",f).width(k.width-2)),!0===d.p.autosearch&&a("input",f).keypress(function(a){return 13==(a.charCode?a.charCode:a.keyCode?a.keyCode:0)?(l(),!1):this})}"horizontal"==d.p.formtype?(!0===d.p.gridToolbar&&!1===d.p.gridNames?a(b).append(f):a(b).append(c).append(f),a(b).append(f)):(g=document.createElement("tr"),a(g).append(c).append(f),
a(n).append(g))});f=document.createElement("td");!0===d.p.enableSearch&&(h="<input type='button' id='sButton' class='"+d.p.buttonclass+"' value='"+d.p.searchButton+"'/>",a(f).append(h),a("input#sButton",f).click(function(){l();return!1}));!0===d.p.enableClear&&(h="<input type='button' id='cButton' class='"+d.p.buttonclass+"' value='"+d.p.clearButton+"'/>",a(f).append(h),a("input#cButton",f).click(function(){e();return!1}));if(!0===d.p.enableClear||!0===d.p.enableSearch)"horizontal"==d.p.formtype?
a(b).append(f):(g=document.createElement("tr"),a(g).append("<td>&#160;</td>").append(f),a(n).append(g))})();a(this).append(m);this.triggerSearch=l;this.clearSearch=e}else alert("Could not get grid colModel")}else alert("No target grid is set!")})}})})(jQuery);
