(function(a){"function"===typeof define&&define.amd?define(["jquery","./jqdnr","./jqmodal"],a):"object"===typeof exports?a(require("jquery")):a(jQuery)})(function(a){var m=a.jgrid,B=m.getMethod("getGridRes"),z=function(a,b){return m.mergeCssClasses(m.getRes(m.guiStyles[this.p.guiStyle||m.defaults.guiStyle||"jQueryUI"],a),b||"")};m.jqModal=m.jqModal||{};a.extend(!0,m.jqModal,{toTop:!0});a.extend(m,{showModal:function(a){a.w.show()},closeModal:function(a){a.w.hide().attr("aria-hidden","true");a.o&&
a.o.remove()},hideModal:function(e,b){b=a.extend({jqm:!0,gb:"",removemodal:!1,formprop:!1,form:""},b||{});var c=b.gb&&"string"===typeof b.gb&&"#gbox_"===b.gb.substr(0,6)?a("#"+b.gb.substr(6))[0]:!1,f=a(e);if(b.onClose){var g=c?b.onClose.call(c,e):b.onClose(e);if("boolean"===typeof g&&!g)return}if(b.formprop&&c&&b.form&&0<f.length){g=f[0].style.height;-1<g.indexOf("px")&&(g=parseFloat(g));var h,d;"edit"===b.form?(h="#"+m.jqID("FrmGrid_"+b.gb.substr(6)),d="formProp"):"view"===b.form&&(h="#"+m.jqID("ViewGrid_"+
b.gb.substr(6)),d="viewProp");a(c).data(d,{top:parseFloat(f.css("top")),left:parseFloat(f.css("left")),width:f.width(),height:g,dataheight:a(h).height(),datawidth:a(h).width()})}if(a.fn.jqm&&!0===b.jqm)f.attr("aria-hidden","true").jqmHide();else{if(""!==b.gb)try{a(">.jqgrid-overlay",b.gb).first().hide()}catch(l){}f.hide().attr("aria-hidden","true")}b.removemodal&&f.remove()},findPos:function(a){var b=0,c=0;if(a.offsetParent){do b+=a.offsetLeft,c+=a.offsetTop,a=a.offsetParent;while(a)}return[b,c]},
createModal:function(e,b,c,f,g,h,d){var l=m.jqID,k=this.p;c=a.extend(!0,{resizingRightBottomIcon:"ui-icon ui-icon-gripsmall-diagonal-se"},m.jqModal||{},null!=k?k.jqModal||{}:{},c);var n=document.createElement("div"),q="#"+l(e.themodal),t="rtl"===a(c.gbox).attr("dir")?!0:!1,x=e.resizeAlso?"#"+l(e.resizeAlso):!1;d=a.extend({},d||{});n.className=z.call(this,"dialog.window","ui-jqdialog");n.id=e.themodal;n.dir=t?"rtl":"ltr";var p=document.createElement("div");p.className=z.call(this,"dialog.header","ui-jqdialog-titlebar "+
(t?"ui-jqdialog-titlebar-rtl":"ui-jqdialog-titlebar-ltr"));p.id=e.modalhead;a(p).append("<span class='ui-jqdialog-title'>"+c.caption+"</span>");var y=z.call(this,"states.hover"),u=a("<a class='ui-jqdialog-titlebar-close ui-corner-all'></a>").hover(function(){u.addClass(y)},function(){u.removeClass(y)}).append("<span class='"+m.getIconRes(k.iconSet,"form.close")+"'></span>");a(p).append(u);k=document.createElement("div");a(k).addClass(z.call(this,"dialog.content","ui-jqdialog-content")).attr("id",
e.modalcontent);a(k).append(b);n.appendChild(k);a(n).prepend(p);!0===h?a("body").append(n):"string"===typeof h?a(h).append(n):a(n).insertBefore(f);a(n).css(d);void 0===c.jqModal&&(c.jqModal=!0);b={};if(a.fn.jqm&&!0===c.jqModal)0===c.left&&0===c.top&&c.overlay&&(h=[],h=m.findPos(g),c.left=h[0]+4,c.top=h[1]+4),b.top=c.top+"px",b.left=c.left;else if(0!==c.left||0!==c.top)b.left=c.left,b.top=c.top+"px";a("a.ui-jqdialog-titlebar-close",p).click(function(){var b=a(q).data("onClose")||c.onClose,e=a(q).data("gbox")||
c.gbox;m.hideModal(q,{gb:e,jqm:c.jqModal,onClose:b,removemodal:c.removemodal||!1,formprop:!c.recreateForm||!1,form:c.form||""});return!1});0!==c.width&&c.width||(c.width=300);0!==c.height&&c.height||(c.height=200);c.zIndex||((f=a(f).parents("*[role=dialog]").first().css("z-index"))?(c.zIndex=parseInt(f,10)+2,c.toTop=!0):c.zIndex=950);b.left&&(b.left+="px");a(n).css(a.extend({width:isNaN(c.width)?"auto":c.width+"px",height:isNaN(c.height)?"auto":c.height+"px",zIndex:c.zIndex,overflow:"hidden"},b)).attr({tabIndex:"-1",
role:"dialog","aria-labelledby":e.modalhead,"aria-hidden":"true"});void 0===c.drag&&(c.drag=!0);void 0===c.resize&&(c.resize=!0);if(c.drag)if(a.fn.jqDrag)a(p).css("cursor","move"),a(n).jqDrag(p);else try{a(n).draggable({handle:a("#"+l(p.id))})}catch(r){}if(c.resize)if(a.fn.jqResize)a(n).append("<div class='jqResize ui-resizable-handle ui-resizable-se "+c.resizingRightBottomIcon+"'></div>"),a(q).jqResize(".jqResize",x);else try{a(n).resizable({handles:"se, sw",alsoResize:x})}catch(r){}!0===c.closeOnEscape&&
a(n).keydown(function(b){27===b.which&&(b=a(q).data("onClose")||c.onClose,m.hideModal(q,{gb:c.gbox,jqm:c.jqModal,onClose:b,removemodal:c.removemodal||!1,formprop:!c.recreateForm||!1,form:c.form||""}))})},viewModal:function(e,b){b=a.extend(!0,{overlay:30,modal:!1,overlayClass:"ui-widget-overlay",onShow:m.showModal,onHide:m.closeModal,gbox:"",jqm:!0,jqM:!0},m.jqModal||{},b||{});if(a.fn.jqm&&!0===b.jqm)b.jqM?a(e).attr("aria-hidden","false").jqm(b).jqmShow():a(e).attr("aria-hidden","false").jqmShow();
else{""!==b.gbox&&(a(">.jqgrid-overlay",b.gbox).first().show(),a(e).data("gbox",b.gbox));a(e).show().attr("aria-hidden","false");try{a(":input:visible",e)[0].focus()}catch(c){}}},info_dialog:function(e,b,c,f){var g=this,h=g.p,d=a.extend(!0,{width:290,height:"auto",dataheight:"auto",drag:!0,resize:!1,left:250,top:170,zIndex:1E3,jqModal:!0,modal:!1,closeOnEscape:!0,align:"center",buttonalign:"center",buttons:[]},m.jqModal||{},null!=h?h.jqModal||{}:{},{caption:"<b>"+e+"</b>"},f||{}),l=d.jqModal;a.fn.jqm&&
!l&&(l=!1);e="";var k=z.call(g,"states.hover");if(0<d.buttons.length)for(f=0;f<d.buttons.length;f++)void 0===d.buttons[f].id&&(d.buttons[f].id="info_button_"+f),e+=m.builderFmButon.call(g,d.buttons[f].id,d.buttons[f].text);f=isNaN(d.dataheight)?d.dataheight:d.dataheight+"px";b="<div id='info_id'>"+("<div id='infocnt' style='margin:0px;padding-bottom:1em;width:100%;overflow:auto;position:relative;height:"+f+";"+("text-align:"+d.align+";")+"'>"+b+"</div>");if(c||""!==e)b+="<hr class='"+z.call(g,"dialog.hr")+
"' style='margin:1px'/><div style='text-align:"+d.buttonalign+";padding:.8em 0 .5em 0;background-image:none;border-width: 1px 0 0 0;'>"+(c?m.builderFmButon.call(g,"closedialog",c):"")+e+"</div>";b+="</div>";try{"false"===a("#info_dialog").attr("aria-hidden")&&m.hideModal("#info_dialog",{jqm:l}),a("#info_dialog").remove()}catch(n){}m.createModal.call(g,{themodal:"info_dialog",modalhead:"info_head",modalcontent:"info_content",resizeAlso:"infocnt"},b,d,"","",!0);e&&a.each(d.buttons,function(b){a("#"+
m.jqID(g.id),"#info_id").bind("click",function(){d.buttons[b].onClick.call(a("#info_dialog"));return!1})});a("#closedialog","#info_id").click(function(){m.hideModal("#info_dialog",{jqm:l,onClose:a("#info_dialog").data("onClose")||d.onClose,gb:a("#info_dialog").data("gbox")||d.gbox});return!1});a(".fm-button","#info_dialog").hover(function(){a(this).addClass(k)},function(){a(this).removeClass(k)});a.isFunction(d.beforeOpen)&&d.beforeOpen();m.viewModal("#info_dialog",{onHide:function(a){a.w.hide().remove();
a.o&&a.o.remove()},modal:d.modal,jqm:l});a.isFunction(d.afterOpen)&&d.afterOpen();try{a("#info_dialog").focus()}catch(n){}},bindEv:function(e,b){a.isFunction(b.dataInit)&&b.dataInit.call(this,e,b);b.dataEvents&&a.each(b.dataEvents,function(){void 0!==this.data?a(e).bind(this.type,this.data,this.fn):a(e).bind(this.type,this.fn)})},createEl:function(e,b,c,f,g){function h(b,c,e){var d="dataInit dataEvents dataUrl buildSelect sopt searchhidden defaultValue attr custom_element custom_value selectFilled rowId mode".split(" ");
void 0!==e&&a.isArray(e)&&a.merge(d,e);a.each(c,function(c,e){-1===a.inArray(c,d)&&a(b).attr(c,e)});c.hasOwnProperty("id")||a(b).attr("id",m.randId())}var d="",l=this,k=l.p,n=m.info_dialog,q=B.call(a(l),"errors.errcap"),t=B.call(a(l),"edit"),x=t.msg,t=t.bClose;switch(e){case "textarea":d=document.createElement("textarea");f?b.cols||a(d).css({width:"100%","box-sizing":"border-box"}):b.cols||(b.cols=20);b.rows||(b.rows=2);if("&nbsp;"===c||"&#160;"===c||1===c.length&&160===c.charCodeAt(0))c="";d.value=
c;h(d,b);a(d).attr({role:"textbox"});break;case "checkbox":d=document.createElement("input");d.type="checkbox";if(b.value){var p=b.value.split(":");c===p[0]&&(d.checked=!0,d.defaultChecked=!0);d.value=p[0];a(d).data("offval",p[1])}else p=String(c).toLowerCase(),0>p.search(/(false|f|0|no|n|off|undefined)/i)&&""!==p?(d.checked=!0,d.defaultChecked=!0,d.value=c):d.value="on",a(d).data("offval","off");h(d,b,["value"]);a(d).attr({role:"checkbox","aria-checked":d.checked?"true":"false"});break;case "select":d=
document.createElement("select");e=[];f=k.iColByName[b.name];n=k.colModel[f];!0===b.multiple?(q=!0,d.multiple="multiple",a(d).attr("aria-multiselectable","true"),e=c.split(","),e=a.map(e,function(b){return a.trim(b)})):(q=!1,e[0]=a.trim(c));void 0===b.size&&(b.size=q?3:1);if(void 0!==b.dataUrl){var p=null,y=b.postData||g.postData,u={elem:d,options:b,cm:n,iCol:f,ovm:e};try{p=b.rowId}catch(A){}k&&k.idPrefix&&(p=m.stripPref(k.idPrefix,p));a.ajax(a.extend({url:a.isFunction(b.dataUrl)?b.dataUrl.call(l,
p,c,String(b.name),u):b.dataUrl,type:"GET",dataType:"html",data:a.isFunction(y)?y.call(l,p,c,String(b.name)):y,context:u,success:function(b,c,e){var d=this.ovm,f=this.elem,g=this.cm,k=this.iCol,n=a.extend({},this.options);b=a.isFunction(n.buildSelect)?n.buildSelect.call(l,b,e,g,k):b;"string"===typeof b&&(b=a(a.trim(b)).html());b&&(a(f).append(b),h(f,n,y?["postData"]:void 0),setTimeout(function(){var b;a("option",f).each(function(c){0===c&&f.multiple&&(this.selected=!1);-1<a.inArray(a.trim(a(this).val()),
d)&&(this.selected="selected",b=!0)});b||a("option",f).each(function(){-1<a.inArray(a.trim(a(this).text()),d)&&(this.selected="selected")});m.fullBoolFeedback.call(l,n.selectFilled,"jqGridSelectFilled",{elem:f,options:n,cm:g,cmName:g.name,iCol:k})},0))}},g||{}))}else if(b.value){"function"===typeof b.value&&(b.value=b.value());var r,v;g=[];var w,k=void 0===b.separator?":":b.separator;v=void 0===b.delimiter?";":b.delimiter;x=function(b,a){if(0<a)return b};if("string"===typeof b.value)for(v=b.value.split(v),
r=0;r<v.length;r++)t=v[r].split(k),2<t.length&&(t[1]=a.map(t,x).join(k)),g.push({value:t[0],innerHtml:t[1],selectValue:a.trim(t[0]),selectText:a.trim(t[1])});else if("object"===typeof b.value)for(r in k=b.value,k)k.hasOwnProperty(r)&&g.push({value:r,innerHtml:k[r],selectValue:a.trim(r),selectText:a.trim(k[r])});for(r=0;r<g.length;r++)w=g[r],u=document.createElement("option"),u.value=w.value,u.innerHTML=w.innerHtml,d.appendChild(u),q||w.selectValue!==a.trim(c)||(u.selected="selected",p=!0),q&&-1<a.inArray(w.selectValue,
e)&&(u.selected="selected",p=!0);if(!p)for(r=0;r<w.length;r++)q||w.selectText!==a.trim(c)||(u.selected="selected"),q&&-1<a.inArray(w.selectText,e)&&(u.selected="selected");h(d,b,["value"]);m.fullBoolFeedback.call(l,b.selectFilled,"jqGridSelectFilled",{elem:d,options:b,cm:n,cmName:n.name,iCol:f})}break;case "text":case "password":case "button":p="button"===e?"button":"textbox";d=document.createElement("input");d.type=e;h(d,b);d.value=c;"button"!==e&&(f?b.size||a(d).css({width:"100%","box-sizing":"border-box"}):
b.size||(b.size=20));a(d).attr("role",p);break;case "image":case "file":d=document.createElement("input");d.type=e;h(d,b);break;case "custom":d=document.createElement("span");try{if(a.isFunction(b.custom_element))if(v=b.custom_element.call(l,c,b),v instanceof jQuery||m.isHTMLElement(v)||"string"===typeof v)v=a(v).addClass("customelement").attr({id:b.id,name:b.name}),a(d).empty().append(v);else throw"editoptions.custom_element returns value of a wrong type";else throw"editoptions.custom_element is not a function";
}catch(A){"e1"===A&&n.call(l,q,"function 'custom_element' "+x.nodefined,t),"e2"===A?n.call(l,q,"function 'custom_element' "+x.novalue,t):n.call(l,q,"string"===typeof A?A:A.message,t)}}return d},checkDate:function(a,b){var c={},f;a=a.toLowerCase();f=-1!==a.indexOf("/")?"/":-1!==a.indexOf("-")?"-":-1!==a.indexOf(".")?".":"/";a=a.split(f);b=b.split(f);if(3!==b.length)return!1;var g=-1,h,d=f=-1,l;for(l=0;l<a.length;l++)h=isNaN(b[l])?0:parseInt(b[l],10),c[a[l]]=h,h=a[l],-1!==h.indexOf("y")&&(g=l),-1!==
h.indexOf("m")&&(d=l),-1!==h.indexOf("d")&&(f=l);h="y"===a[g]||"yyyy"===a[g]?4:"yy"===a[g]?2:-1;var k;l=[0,31,29,31,30,31,30,31,31,30,31,30,31];if(-1===g)return!1;k=c[a[g]].toString();2===h&&1===k.length&&(h=1);if(k.length!==h||0===c[a[g]]&&"00"!==b[g]||-1===d)return!1;k=c[a[d]].toString();if(1>k.length||1>c[a[d]]||12<c[a[d]]||-1===f)return!1;k=c[a[f]].toString();!(h=1>k.length||1>c[a[f]]||31<c[a[f]])&&(h=2===c[a[d]])&&(g=c[a[g]],h=c[a[f]]>(0!==g%4||0===g%100&&0!==g%400?28:29));return h||c[a[f]]>
l[c[a[d]]]?!1:!0},isEmpty:function(a){return a.match(/^\s+$/)||""===a?!0:!1},checkTime:function(a){var b=/^(\d{1,2}):(\d{2})([apAP][Mm])?$/;if(!m.isEmpty(a))if(a=a.match(b)){if(a[3]){if(1>a[1]||12<a[1])return!1}else if(23<a[1])return!1;if(59<a[2])return!1}else return!1;return!0},checkValues:function(e,b,c,f){var g,h,d=this.p;h=d.colModel;var l=m.isEmpty,k=B.call(a(this),"edit.msg"),n=B.call(a(this),"formatter.date.masks");if(void 0===c){"string"===typeof b&&(b=d.iColByName[b]);if(void 0===b||0>b)return[!0,
"",""];f=h[b];c=f.editrules;null!=f.formoptions&&(g=f.formoptions.label)}else g=void 0===f?"_":f,f=h[b];if(c){g||(g=null!=d.colNames?d.colNames[b]:f.label);if(!0===c.required&&l(e))return[!1,g+": "+k.required,""];d=!1===c.required?!1:!0;if(!0===c.number&&(!1!==d||!l(e))&&isNaN(e))return[!1,g+": "+k.number,""];if(void 0!==c.minValue&&!isNaN(c.minValue)&&parseFloat(e)<parseFloat(c.minValue))return[!1,g+": "+k.minValue+" "+c.minValue,""];if(void 0!==c.maxValue&&!isNaN(c.maxValue)&&parseFloat(e)>parseFloat(c.maxValue))return[!1,
g+": "+k.maxValue+" "+c.maxValue,""];var q;if(!(!0!==c.email||!1===d&&l(e)||(q=/^((([a-z]|\d|[!#\$%&'\*\+\-\/=\?\^_`{\|}~]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+(\.([a-z]|\d|[!#\$%&'\*\+\-\/=\?\^_`{\|}~]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])+)*)|((\x22)((((\x20|\x09)*(\x0d\x0a))?(\x20|\x09)+)?(([\x01-\x08\x0b\x0c\x0e-\x1f\x7f]|\x21|[\x23-\x5b]|[\x5d-\x7e]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(\\([\x01-\x09\x0b\x0c\x0d-\x7f]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]))))*(((\x20|\x09)*(\x0d\x0a))?(\x20|\x09)+)?(\x22)))@((([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.)+(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.?$/i,
q.test(e))))return[!1,g+": "+k.email,""];if(!(!0!==c.integer||!1===d&&l(e)||!isNaN(e)&&0===e%1&&-1===e.indexOf(".")))return[!1,g+": "+k.integer,""];if(!(!0!==c.date||!1===d&&l(e)||(f.formatoptions&&f.formatoptions.newformat?(h=f.formatoptions.newformat,n.hasOwnProperty(h)&&(h=n[h])):h=h[b].datefmt||"Y-m-d",m.checkDate(h,e))))return[!1,g+": "+k.date+" - "+h,""];if(!0===c.time&&!(!1===d&&l(e)||m.checkTime(e)))return[!1,g+": "+k.date+" - hh:mm (am/pm)",""];if(!(!0!==c.url||!1===d&&l(e)||(q=/^(((https?)|(ftp)):\/\/([\-\w]+\.)+\w{2,3}(\/[%\-\w]+(\.\w{2,})?)*(([\w\-\.\?\\\/+@&#;`~=%!]*)(\.\w{2,})?)*\/?)/i,
q.test(e))))return[!1,g+": "+k.url,""];if(!0===c.custom&&(!1!==d||!l(e)))return a.isFunction(c.custom_func)?(e=c.custom_func.call(this,e,g,b),a.isArray(e)?e:[!1,k.customarray,""]):[!1,k.customfcheck,""]}return[!0,"",""]}})});
/*
//# sourceMappingURL=grid.common.map
*/