(function(m){"function"===typeof define&&define.amd?define(["jquery","./grid.grouping"],m):"object"===typeof exports?m(require("jquery")):m(jQuery)})(function(m){function J(d,c,k){if(!(this instanceof J))return new J(d);this.aggregator=d;this.finilized=!1;this.context=c;this.pivotOptions=k}function D(d,c,k,l,n){var f=l.length,x=function(a,b){var d=a,c=b;null==d&&(d="");null==c&&(c="");d=String(d);c=String(c);this.caseSensitive||(d=d.toUpperCase(),c=c.toUpperCase());if(d===c){if(a===b)return 0;if(void 0===
a)return-1;if(void 0===b)return 1;if(null===a)return-1;if(null===b)return 1}return d<c?-1:1},g=function(a,b){a=Number(a);b=Number(b);return a===b?0:a<b?-1:1},e=function(a,b){a=Math.floor(Number(a));b=Math.floor(Number(b));return a===b?0:a<b?-1:1};this.items=[];this.indexesOfSourceData=[];this.trimByCollect=d;this.caseSensitive=c;this.skipSort=k;this.fieldLength=f;this.fieldNames=Array(f);this.fieldSortDirection=Array(f);this.fieldCompare=Array(f);for(d=0;d<f;d++){c=l[d];this.fieldNames[d]=c[n||"dataName"];
switch(c.sorttype){case "integer":case "int":this.fieldCompare[d]=e;break;case "number":case "currency":case "float":this.fieldCompare[d]=g;break;default:this.fieldCompare[d]=m.isFunction(c.compare)?c.compare:x}this.fieldSortDirection[d]="desc"===c.sortorder?-1:1}}var Q=m.jgrid;J.prototype.calc=function(d,c,k,l,n){if(void 0!==d)switch(this.result=this.result||0,d=parseFloat(d),this.aggregator){case "sum":this.result+=d;break;case "count":this.result++;break;case "avg":this.finilized?(this.count=this.count||
0,this.result=(this.result*this.count+d)/(this.count+1)):(this.result+=d,this.count=this.count||0);this.count++;break;case "min":this.result=Math.min(this.result,d);break;case "max":this.result=Math.max(this.result,d);break;default:m.isFunction(this.aggregator)&&(this.result=this.aggregator.call(this.context,{previousResult:this.result,value:d,fieldName:c,item:k,iItem:l,items:n}))}};J.prototype.getResult=function(d,c,k){if(void 0!==this.result||k)k&&void 0!==this.result&&(this.count=this.result=0),
void 0===this.result||this.finilized||"avg"!==this.aggregator||(this.result/=this.count,this.finilized=!0),d[c]=this.result};D.prototype.compareVectorsEx=function(d,c){var k=this.fieldLength,l,m;for(l=0;l<k;l++)if(m=this.fieldCompare[l](d[l],c[l]),0!==m)return{index:l,result:m};return{index:-1,result:0}};D.prototype.getIndexOfDifferences=function(d,c){return null===c||null===d?0:this.compareVectorsEx(d,c).index};D.prototype.compareVectors=function(d,c){var k=this.compareVectorsEx(d,c);return 0<(0<=
k.index?this.fieldSortDirection[k.index]:1)?k.result:-k.result};D.prototype.getItem=function(d){return this.items[d]};D.prototype.getIndexLength=function(){return this.items.length};D.prototype.getIndexesOfSourceData=function(d){return this.indexesOfSourceData[d]};D.prototype.createDataIndex=function(d){var c,k=d.length,l=this.fieldLength,n,f,x=this.fieldNames,g=this.indexesOfSourceData,e,a,b=this.items,r;for(c=0;c<k;c++){a=d[c];n=Array(l);for(e=0;e<l;e++)f=a[x[e]],void 0!==f&&("string"===typeof f&&
this.trimByCollect&&(f=m.trim(f)),n[e]=f);a=0;r=b.length-1;if(0>r)b.push(n),g.push([c]);else if(f=this.compareVectors(n,b[r]),0===f)g[r].push(c);else if(1===f||this.skipSort)b.push(n),g.push([c]);else if(f=this.compareVectors(b[0],n),1===f)b.unshift(n),g.unshift([c]);else if(0===f)g[0].push(c);else for(;;){if(2>r-a){b.splice(r,0,n);g.splice(r,0,[c]);break}e=Math.floor((a+r)/2);f=this.compareVectors(b[e],n);if(0===f){g[e].push(c);break}1===f?r=e:a=e}}};Q.extend({pivotSetup:function(d,c){var k=this[0],
l=m.isArray,n={},f={groupField:[],groupSummary:[],groupSummaryPos:[]},x={grouping:!0,groupingView:f},g=m.extend({totals:!1,useColSpanStyle:!1,trimByCollect:!0,skipSortByX:!1,skipSortByY:!1,caseSensitive:!1,footerTotals:!1,groupSummary:!0,groupSummaryPos:"header",frozenStaticCols:!1,defaultFormatting:!0,data:d},c||{}),e,a,b,r=d.length,E,h,p,y,B,U,R=g.xDimension,M=g.yDimension,F=g.aggregates,N,r=g.totalText||g.totals||g.rowTotals||g.totalHeader,t,G=l(R)?R.length:0;y=l(M)?M.length:0;var q=l(F)?F.length:
0,z=y-(1===q?1:0),H=[],K=[],O=[],l=[],V=Array(q),P=Array(y),S,Y,w,W,L,I,A,u,C,T,v;a=function(a,b,c){a=new D(g.trimByCollect,g.caseSensitive,b,a);m.isFunction(c)&&(a.compareVectorsEx=c);a.createDataIndex(d);return a};var aa=function(a,b,d,c,f){var e,h;switch(a){case 1:e=M[c].totalText||"{0} {1} {2}";h="y"+f+"t"+c;break;case 2:e=g.totalText||"{0}";h="t";break;default:e=1<q?b.label||"{0}":v.getItem(f)[c],h="y"+f}a=m.extend({},b,{name:h+(1<q?"a"+d:""),label:m.isFunction(e)?e.call(k,2===a?{aggregate:b,
iAggregate:d,pivotOptions:g}:{yIndex:v.getItem(f),aggregate:b,iAggregate:d,yLevel:c,pivotOptions:g}):Q.template.apply(k,2===a?[e,b.aggregator,b.member,d]:[e,b.aggregator,b.member,v.getItem(f)[c],c])});delete a.member;delete a.aggregator;return a};B=function(a,b,c){var d,e;for(d=0;d<q;d++)e=F[d],void 0===e.template&&void 0===e.formatter&&g.defaultFormatting&&(e.template="count"===e.aggregator?"integer":"number"),O.push(aa(a,e,d,b,c))};S=function(a,b,d){var c,e,f,g;for(c=z-1;c>=b;c--)if(K[c]){for(e=
0;e<=c;e++)C=H[e].groupHeaders,C[C.length-1].numberOfColumns+=q;E=M[c];f=E.totalHeader;g=E.headerOnTop;for(e=c+1;e<=z-1;e++)H[e].groupHeaders.push({titleText:g&&e===c+1||!g&&e===z-1?m.isFunction(f)?f.call(k,d,c):Q.template.call(k,f||"",d[c],c):"",startColumnName:"y"+(a-1)+"t"+c+(1===q?"":"a0"),numberOfColumns:q})}};var X=function(a){a=new J("count"===F[a].aggregator?"sum":F[a].aggregator,k,c);a.groupInfo={iRows:[],rows:[],ys:[],iYs:[]};return a},ba=function(){var a,b;for(a=z-1;0<=a;a--)if(K[a])for(null==
P[a]&&(P[a]=Array(q)),b=0;b<q;b++)P[a][b]=X(b)},Z=function(a,b,c,d){var e,f=v.getIndexOfDifferences(b,c),g,h;if(null!==c)for(f=Math.max(f,0),e=z-1;e>=f;e--)g="y"+a+"t"+e+(1<q?"a"+d:""),K[e]&&void 0===A[g]&&(h=P[e][d],h.getResult(A,g),A.pivotInfos[g]={colType:1,iA:d,a:F[d],level:e,iRows:h.groupInfo.iRows,rows:h.groupInfo.rows,ys:h.groupInfo.ys,iYs:h.groupInfo.iYs},b!==c&&(P[e][d]=X(d)))},ca=function(a,b,c,e,f,g,h){var k;if(a!==b)for(b=z-1;0<=b;b--)K[b]&&(k=P[b][e],k.calc(f[c.member],c.member,f,g,d),
k=k.groupInfo,0>m.inArray(h,k.iYs)&&(k.iYs.push(h),k.ys.push(a)),0>m.inArray(g,k.iRows)&&(k.iRows.push(g),k.rows.push(f)))};if(0===G||0===q)throw"xDimension or aggregates options are not set!";T=a(R,g.skipSortByX,g.compareVectorsByX);v=a(M,g.skipSortByY,g.compareVectorsByY);c.xIndex=T;c.yIndex=v;for(a=0;a<G;a++)b=R[a],h={name:"x"+a,label:null!=b.label?m.isFunction(b.label)?b.label.call(k,b,a,g):b.label:b.dataName,frozen:g.frozenStaticCols},a<G-1&&(f.groupField.push(h.name),f.groupSummary.push(g.groupSummary),
f.groupSummaryPos.push(g.groupSummaryPos)),h=m.extend(h,b),delete h.dataName,delete h.footerText,O.push(h);2>G&&(x.grouping=!1);x.sortname=O[G-1].name;f.hideFirstGroupCol=!0;for(a=0;a<y;a++)E=M[a],K.push(E.totals||E.rowTotals||E.totalText||E.totalHeader?!0:!1);u=v.getItem(0);B(0,y-1,0);f=v.getIndexLength();for(h=1;h<f;h++){w=v.getItem(h);a=v.getIndexOfDifferences(w,u);for(b=z-1;b>=a;b--)K[b]&&B(1,b,h-1);u=w;B(0,y-1,h)}for(a=z-1;0<=a;a--)K[a]&&B(1,a,f-1);r&&B(2);u=v.getItem(0);for(b=0;b<z;b++)H.push({useColSpanStyle:g.useColSpanStyle,
groupHeaders:[{titleText:u[b],startColumnName:1===q?"y0":"y0a0",numberOfColumns:q}]});for(h=1;h<f;h++){w=v.getItem(h);a=v.getIndexOfDifferences(w,u);S(h,a,u);for(b=z-1;b>=a;b--)H[b].groupHeaders.push({titleText:w[b],startColumnName:"y"+h+(1===q?"":"a0"),numberOfColumns:q});for(b=0;b<a;b++)C=H[b].groupHeaders,C[C.length-1].numberOfColumns+=q;u=w}S(f,0,u);if(r)for(a=0;a<z;a++)H[a].groupHeaders.push({titleText:a<z-1?"":g.totalHeader||"",startColumnName:"t"+(1===q?"":"a0"),numberOfColumns:q});S=T.getIndexLength();
for(y=0;y<S;y++){b=T.getItem(y);B={iX:y,x:b};A={pivotInfos:B};for(a=0;a<G;a++)A["x"+a]=b[a];Y=T.getIndexesOfSourceData(y);if(r)for(b=0;b<q;b++)V[b]=X(b);u=null;ba();for(h=0;h<f;h++){w=v.getItem(h);W=v.getIndexesOfSourceData(h);for(b=0;b<q;b++){null!==u&&Z(h-1,w,u,b);L=[];for(a=0;a<W.length;a++)p=W[a],0<=m.inArray(p,Y)&&L.push(p);if(0<L.length){U=Array(L.length);I=F[b];N=new J(I.aggregator,k,c);for(p=0;p<L.length;p++)a=L[p],e=d[a],U[p]=e,N.calc(e[I.member],I.member,e,a,d),r&&(t=V[b],t.calc(e[I.member],
I.member,e,a,d),t=t.groupInfo,0>m.inArray(a,t.iYs)&&(t.iYs.push(h),t.ys.push(w)),0>m.inArray(a,t.iRows)&&(t.iRows.push(a),t.rows.push(e))),ca(w,u,I,b,e,a,h);e="y"+h+(1===q?"":"a"+b);N.getResult(A,e);B[e]={colType:0,iY:h,y:w,iA:b,a:I,iRows:L,rows:U}}}u=w}if(null!==u)for(b=0;b<q;b++)Z(f-1,u,u,b);if(r)for(b=0;b<q;b++)e="t"+(1===q?"":"a"+b),t=V[b],t.getResult(A,e),t=t.groupInfo,B[e]={colType:2,iA:b,a:F[b],iRows:t.iRows,rows:t.rows,iYs:t.iYs,ys:t.ys};l.push(A)}if(g.footerTotals||g.colTotals){r=l.length;
for(a=0;a<G;a++)n["x"+a]=R[a].footerText||"";for(a=G;a<O.length;a++){e=O[a].name;N=new J(g.footerAggregator||"sum",k,c);for(p=0;p<r;p++)A=l[p],N.calc(A[e],e,A,p,l);N.getResult(n,e)}}c.colHeaders=H;return{colModel:O,options:c,rows:l,groupOptions:x,groupHeaders:H,summary:n}},jqPivot:function(d,c,k,l){return this.each(function(){function n(d){var a=g.pivotSetup.call(x,d,c),b=a.groupHeaders,l=a.summary,n=0,h;for(h in l)l.hasOwnProperty(h)&&n++;l=0<n?!0:!1;n=a.groupOptions.groupingView;h=Q.from.call(f,
a.rows);var p;if(c.skipSortByX)for(p=0;p<n.groupField.length;p++)h.orderBy(n.groupField[p],null!=k&&k.groupingView&&null!=k.groupingView.groupOrder&&"desc"===k.groupingView.groupOrder[p]?"d":"a","text","");c.data=d;g.call(x,m.extend(!0,{datastr:m.extend(h.select(),l?{userdata:a.summary}:{}),datatype:"jsonstring",footerrow:l,userDataOnFooter:l,colModel:a.colModel,pivotOptions:a.options,additionalProperties:["pivotInfos"],viewrecords:!0,sortname:c.xDimension[0].dataName},a.groupOptions,k||{}));if(b.length)for(p=
0;p<b.length;p++)b[p]&&b[p].groupHeaders.length&&g.setGroupHeaders.call(x,b[p]);c.frozenStaticCols&&g.setFrozenColumns.call(x)}var f=this,x=m(f),g=m.fn.jqGrid;"string"===typeof d?m.ajax(m.extend({url:d,dataType:"json",success:function(c){n(Q.getAccessor(c,l&&l.reader?l.reader:"rows"))}},l||{})):n(d)})}})});
/*
//# sourceMappingURL=grid.pivot.map
*/