(function(b){"function"===typeof define&&define.amd?define(["jquery","./grid.base","./grid.common"],b):"object"===typeof exports?b(require("jquery")):b(jQuery)})(function(b){var l=b.jgrid;b.fn.jqFilter=function(k){if("string"===typeof k){var q=b.fn.jqFilter[k];if(!q)throw"jqFilter - No such method: "+k;var E=b.makeArray(arguments).slice(1);return q.apply(this,E)}var c=b.extend(!0,{filter:null,columns:[],onChange:null,afterRedraw:null,checkValues:null,error:!1,errmsg:"",errorcheck:!0,showQuery:!0,
sopt:null,ops:[],operands:null,numopts:"eq ne lt le gt ge nu nn in ni".split(" "),stropts:"eq ne bw bn ew en cn nc nu nn in ni".split(" "),strarr:["text","string","blob"],groupOps:[{op:"AND",text:"AND"},{op:"OR",text:"OR"}],groupButton:!0,ruleButtons:!0,direction:"ltr"},l.filter,k||{});return this.each(function(){if(!this.filter){this.p=c;if(null===c.filter||void 0===c.filter)c.filter={groupOp:c.groupOps[0].op,rules:[],groups:[]};var k,q=c.columns.length,e,B=/msie/i.test(navigator.userAgent)&&!window.opera,
y=function(){return b("#"+l.jqID(c.id))[0]||null},A=l.getRes(l.guiStyles[y().p.guiStyle],"states.error"),C=l.getRes(l.guiStyles[y().p.guiStyle],"dialog.content");c.initFilter=b.extend(!0,{},c.filter);if(q){for(k=0;k<q;k++)e=c.columns[k],e.stype?e.inputtype=e.stype:e.inputtype||(e.inputtype="text"),e.sorttype?e.searchtype=e.sorttype:e.searchtype||(e.searchtype="string"),void 0===e.hidden&&(e.hidden=!1),e.label||(e.label=e.name),e.index&&(e.name=e.index),e.hasOwnProperty("searchoptions")||(e.searchoptions=
{}),e.hasOwnProperty("searchrules")||(e.searchrules={});c.showQuery&&b(this).append("<table class='queryresult "+C+"' style='display:block;max-width:440px;border:0px none;' dir='"+c.direction+"'><tbody><tr><td class='query'></td></tr></tbody></table>");var D=function(f,m){var a=[!0,""],g=y();if(b.isFunction(m.searchrules))a=m.searchrules.call(g,f,m);else if(l&&l.checkValues)try{a=l.checkValues.call(g,f,-1,m.searchrules,m.label)}catch(r){}a&&a.length&&!1===a[0]&&(c.error=!a[0],c.errmsg=a[1])};this.onchange=
function(){c.error=!1;c.errmsg="";return b.isFunction(c.onChange)?c.onChange.call(this,c):!1};this.reDraw=function(){b("table.group:first",this).remove();var f=this.createTableForGroup(c.filter,null);b(this).append(f);b.isFunction(c.afterRedraw)&&c.afterRedraw.call(this,c)};this.createTableForGroup=function(f,m){var a=this,g,r=b("<table class='group "+C+"' style='border:0px none;'><tbody></tbody></table>"),d="left";"rtl"===c.direction&&(d="right",r.attr("dir","rtl"));null===m&&r.append("<tr class='error' style='display:none;'><th colspan='5' class='"+
A+"' align='"+d+"'></th></tr>");var h=b("<tr></tr>");r.append(h);d=b("<th colspan='5' align='"+d+"'></th>");h.append(d);if(!0===c.ruleButtons){var k=b("<select class='opsel'></select>");d.append(k);var h="",e;for(g=0;g<c.groupOps.length;g++)e=f.groupOp===a.p.groupOps[g].op?" selected='selected'":"",h+="<option value='"+a.p.groupOps[g].op+"'"+e+">"+a.p.groupOps[g].text+"</option>";k.append(h).bind("change",function(){f.groupOp=b(k).val();a.onchange()})}h="<span></span>";c.groupButton&&(h=b("<input type='button' value='+ {}' title='Add subgroup' class='add-group'/>"),
h.bind("click",function(){void 0===f.groups&&(f.groups=[]);f.groups.push({groupOp:c.groupOps[0].op,rules:[],groups:[]});a.reDraw();a.onchange();return!1}));d.append(h);if(!0===c.ruleButtons){var h=b("<input type='button' value='+' title='Add rule' class='add-rule ui-add'/>"),l;h.bind("click",function(){var c,d,h;void 0===f.rules&&(f.rules=[]);for(g=0;g<a.p.columns.length;g++)if(c=void 0===a.p.columns[g].search?!0:a.p.columns[g].search,d=!0===a.p.columns[g].hidden,(h=!0===a.p.columns[g].searchoptions.searchhidden)&&
c||c&&!d){l=a.p.columns[g];break}c=l.searchoptions.sopt?l.searchoptions.sopt:a.p.sopt?a.p.sopt:-1!==b.inArray(l.searchtype,a.p.strarr)?a.p.stropts:a.p.numopts;f.rules.push({field:l.name,op:c[0],data:""});a.reDraw();return!1});d.append(h)}null!==m&&(h=b("<input type='button' value='-' title='Delete group' class='delete-group'/>"),d.append(h),h.bind("click",function(){for(g=0;g<m.groups.length;g++)if(m.groups[g]===f){m.groups.splice(g,1);break}a.reDraw();a.onchange();return!1}));if(void 0!==f.groups)for(g=
0;g<f.groups.length;g++)d=b("<tr></tr>"),r.append(d),h=b("<td class='first'></td>"),d.append(h),h=b("<td colspan='4'></td>"),h.append(this.createTableForGroup(f.groups[g],f)),d.append(h);void 0===f.groupOp&&(f.groupOp=a.p.groupOps[0].op);if(void 0!==f.rules)for(g=0;g<f.rules.length;g++)r.append(this.createTableRowForRule(f.rules[g],f));return r};this.createTableRowForRule=function(f,m){var a=this,g=y(),k=b("<tr></tr>"),d,h,e,n="",t;k.append("<td class='first'></td>");var p=b("<td class='columns'></td>");
k.append(p);var q=b("<select></select>"),v,u=[];p.append(q);q.bind("change",function(){f.field=b(q).val();var c=b(this).parents("tr:first"),d,m;for(m=0;m<a.p.columns.length;m++)if(a.p.columns[m].name===f.field){d=a.p.columns[m];break}if(d){var e=b.extend({},d.searchoptions||{},{id:l.randId(),name:d.name,mode:"search"});B&&"text"===d.inputtype&&!e.size&&(e.size=10);var k=l.createEl.call(g,d.inputtype,e,"",!0,a.p.ajaxSelectOptions||{},!0);b(k).addClass("input-elm");h=e.sopt?e.sopt:a.p.sopt?a.p.sopt:
-1!==b.inArray(d.searchtype,a.p.strarr)?a.p.stropts:a.p.numopts;d="";var r=0,n,p;u=[];b.each(a.p.ops,function(){u.push(this.oper)});a.p.cops&&b.each(a.p.cops,function(a){u.push(a)});for(m=0;m<h.length;m++)p=h[m],v=b.inArray(h[m],u),-1!==v&&(n=a.p.ops[v],n=void 0!==n?n.text:a.p.cops[p].text,0===r&&(f.op=p),d+="<option value='"+p+"'>"+n+"</option>",r++);b(".selectopts",c).empty().append(d);b(".selectopts",c)[0].selectedIndex=0;l.msie&&9>l.msiever()&&(m=parseInt(b("select.selectopts",c)[0].offsetWidth,
10)+1,b(".selectopts",c).width(m),b(".selectopts",c).css("width","auto"));b(".data",c).empty().append(k);l.bindEv.call(g,k,e);b(".input-elm",c).bind("change",function(d){d=d.target;f.data="SPAN"===d.nodeName.toUpperCase()&&e&&b.isFunction(e.custom_value)?e.custom_value.call(g,b(d).children(".customelement:first"),"get"):d.value;a.onchange()});setTimeout(function(){f.data=b(k).val();a.onchange()},0)}});var p=0,w,x;for(d=0;d<a.p.columns.length;d++)if(t=void 0===a.p.columns[d].search?!0:a.p.columns[d].search,
w=!0===a.p.columns[d].hidden,(x=!0===a.p.columns[d].searchoptions.searchhidden)&&t||t&&!w)t="",f.field===a.p.columns[d].name&&(t=" selected='selected'",p=d),n+="<option value='"+a.p.columns[d].name+"'"+t+">"+a.p.columns[d].label+"</option>";q.append(n);n=b("<td class='operators'></td>");k.append(n);e=c.columns[p];B&&"text"===e.inputtype&&!e.searchoptions.size&&(e.searchoptions.size=10);p=l.createEl.call(g,e.inputtype,b.extend({},e.searchoptions||{},{id:l.randId(),name:e.name}),f.data,!0,a.p.ajaxSelectOptions||
{},!0);if("nu"===f.op||"nn"===f.op)b(p).attr("readonly","true"),b(p).attr("disabled","true");var z=b("<select class='selectopts'></select>");n.append(z);z.bind("change",function(){f.op=b(z).val();var d=b(this).parents("tr:first"),d=b(".input-elm",d)[0];"nu"===f.op||"nn"===f.op?(f.data="","SELECT"!==d.tagName.toUpperCase()&&(d.value=""),d.setAttribute("readonly","true"),d.setAttribute("disabled","true")):("SELECT"===d.tagName.toUpperCase()&&(f.data=d.value),d.removeAttribute("readonly"),d.removeAttribute("disabled"));
a.onchange()});h=e.searchoptions.sopt?e.searchoptions.sopt:a.p.sopt?a.p.sopt:-1!==b.inArray(e.searchtype,a.p.strarr)?a.p.stropts:a.p.numopts;n="";b.each(a.p.ops,function(){u.push(this.oper)});a.p.cops&&b.each(a.p.cops,function(a){u.push(a)});for(d=0;d<h.length;d++)x=h[d],v=b.inArray(h[d],u),-1!==v&&(w=a.p.ops[v],t=f.op===x?" selected='selected'":"",n+="<option value='"+x+"'"+t+">"+(void 0!==w?w.text:a.p.cops[x].text)+"</option>");z.append(n);n=b("<td class='data'></td>");k.append(n);n.append(p);l.bindEv.call(g,
p,e.searchoptions);b(p).addClass("input-elm").bind("change",function(){f.data="custom"===e.inputtype?e.searchoptions.custom_value.call(g,b(this).children(".customelement:first"),"get"):b(this).val();a.onchange()});n=b("<td></td>");k.append(n);!0===c.ruleButtons&&(p=b("<input type='button' value='-' title='Delete rule' class='delete-rule ui-del'/>"),n.append(p),p.bind("click",function(){for(d=0;d<m.rules.length;d++)if(m.rules[d]===f){m.rules.splice(d,1);break}a.reDraw();a.onchange();return!1}));return k};
this.getStringForGroup=function(b){var c="(",a;if(void 0!==b.groups)for(a=0;a<b.groups.length;a++){1<c.length&&(c+=" "+b.groupOp+" ");try{c+=this.getStringForGroup(b.groups[a])}catch(g){alert(g)}}if(void 0!==b.rules)try{for(a=0;a<b.rules.length;a++)1<c.length&&(c+=" "+b.groupOp+" "),c+=this.getStringForRule(b.rules[a])}catch(g){alert(g)}c+=")";return"()"===c?"":c};this.getStringForRule=function(f){var e="",a="",g,k,d=f.data,h;for(g=0;g<c.ops.length;g++)if(c.ops[g].oper===f.op){e=c.operands.hasOwnProperty(f.op)?
c.operands[f.op]:"";a=c.ops[g].oper;break}if(""===a&&null!=c.cops)for(h in c.cops)if(c.cops.hasOwnProperty(h)&&(a=h,e=c.cops[h].operand,b.isFunction(c.cops[h].buildQueryValue)))return c.cops[h].buildQueryValue.call(c,{cmName:f.field,searchValue:d,operand:e});for(g=0;g<c.columns.length;g++)if(c.columns[g].name===f.field){k=c.columns[g];break}if(null==k)return"";if("bw"===a||"bn"===a)d+="%";if("ew"===a||"en"===a)d="%"+d;if("cn"===a||"nc"===a)d="%"+d+"%";if("in"===a||"ni"===a)d=" ("+d+")";c.errorcheck&&
D(f.data,k);return-1!==b.inArray(k.searchtype,["int","integer","float","number","currency"])||"nn"===a||"nu"===a?f.field+" "+e+" "+d:f.field+" "+e+' "'+d+'"'};this.resetFilter=function(){c.filter=b.extend(!0,{},c.initFilter);this.reDraw();this.onchange()};this.hideError=function(){b("th."+A,this).html("");b("tr.error",this).hide()};this.showError=function(){b("th."+A,this).html(c.errmsg);b("tr.error",this).show()};this.toUserFriendlyString=function(){return this.getStringForGroup(c.filter)};this.toString=
function(){function b(a){var c="(",k;if(void 0!==a.groups)for(k=0;k<a.groups.length;k++)1<c.length&&(c="OR"===a.groupOp?c+" || ":c+" && "),c+=b(a.groups[k]);if(void 0!==a.rules)for(k=0;k<a.rules.length;k++){1<c.length&&(c="OR"===a.groupOp?c+" || ":c+" && ");var d=a.rules[k];if(e.p.errorcheck){for(var h=void 0,l=void 0,h=0;h<e.p.columns.length;h++)if(e.p.columns[h].name===d.field){l=e.p.columns[h];break}l&&D(d.data,l)}c+=d.op+"(item."+d.field+",'"+d.data+"')"}c+=")";return"()"===c?"":c}var e=this;
return b(c.filter)};this.reDraw();if(c.showQuery)this.onchange();this.filter=!0}}})};b.extend(b.fn.jqFilter,{toSQLString:function(){var b="";this.each(function(){b=this.toUserFriendlyString()});return b},filterData:function(){var b;this.each(function(){b=this.p.filter});return b},getParameter:function(b){return void 0!==b&&this.p.hasOwnProperty(b)?this.p[b]:this.p},resetFilter:function(){return this.each(function(){this.resetFilter()})},addFilter:function(b){"string"===typeof b&&(b=l.parse(b));this.each(function(){this.p.filter=
b;this.reDraw();this.onchange()})}})});
/*
//# sourceMappingURL=grid.filter.map
*/