(function(e){"function"===typeof define&&define.amd?define(["jquery","./grid.base"],e):"object"===typeof exports?e(require("jquery")):e(jQuery)})(function(e){e.jgrid=e.jgrid||{};var p=e.jgrid,w=p.getMethod("getGridRes");e.fmatter=e.fmatter||{};var q=e.fmatter;e.extend(!0,p,{formatter:{date:{parseRe:/[#%\\\/:_;.,\t\s\-]/,masks:{ISO8601Long:"Y-m-d H:i:s",ISO8601Short:"Y-m-d",SortableDateTime:"Y-m-d\\TH:i:s",UniversalSortableDateTime:"Y-m-d H:i:sO"},reformatAfterEdit:!0,userLocalTime:!1},baseLinkUrl:"",
showAction:"",target:"",checkbox:{disabled:!0},idName:"id"},cmTemplate:{integerStr:{formatter:"integer",align:"right",sorttype:"integer",searchoptions:{sopt:"eq ne lt le gt ge".split(" ")}},integer:{formatter:"integer",align:"right",sorttype:"integer",convertOnSave:function(a){a=a.newValue;return isNaN(a)?a:parseInt(a,10)},searchoptions:{sopt:"eq ne lt le gt ge".split(" ")}},numberStr:{formatter:"number",align:"right",sorttype:"number",searchoptions:{sopt:"eq ne lt le gt ge".split(" ")}},number:{formatter:"number",
align:"right",sorttype:"number",convertOnSave:function(a){a=a.newValue;return isNaN(a)?a:parseFloat(a)},searchoptions:{sopt:"eq ne lt le gt ge".split(" ")}},booleanCheckbox:{align:"center",formatter:"checkbox",edittype:"checkbox",editoptions:{value:"true:false",defaultValue:"false"},convertOnSave:function(a){var b=a.newValue,c=a.cm;a=String(b).toLowerCase();c=null!=c.editoptions&&"string"===typeof c.editoptions.value?c.editoptions.value.split(":"):["yes","no"];0<=e.inArray(a,["1","true",c[0].toLowerCase()])?
b=!0:0<=e.inArray(a,["0","false",c[1].toLowerCase()])&&(b=!1);return b},stype:"select",searchoptions:{sopt:["eq","ne"],value:":Any;true:Yes;false:No"}},booleanCheckboxFa:{align:"center",formatter:"checkboxFontAwesome4",edittype:"checkbox",editoptions:{value:"true:false",defaultValue:"false"},convertOnSave:function(a){var b=a.newValue,c=a.cm;a=String(b).toLowerCase();c=null!=c.editoptions&&"string"===typeof c.editoptions.value?c.editoptions.value.split(":"):["yes","no"];0<=e.inArray(a,["1","true",
c[0].toLowerCase()])?b=!0:0<=e.inArray(a,["0","false",c[1].toLowerCase()])&&(b=!1);return b},stype:"select",searchoptions:{sopt:["eq","ne"],value:":Any;true:Yes;false:No"}},actions:function(){return{formatter:"actions",width:(null!=this.p&&this.p.fontAwesomeIcons?33:37)+(p.cellWidth()?5:0),align:"center",label:"",autoResizable:!1,frozen:!0,fixed:!0,hidedlg:!0,resizable:!1,sortable:!1,search:!1,editable:!1,viewable:!1}}}});e.extend(q,{isObject:function(a){return a&&("object"===typeof a||e.isFunction(a))||
!1},isNumber:function(a){return"number"===typeof a&&isFinite(a)},isValue:function(a){return this.isObject(a)||"string"===typeof a||this.isNumber(a)||"boolean"===typeof a},isEmpty:function(a){if("string"!==typeof a&&this.isValue(a))return!1;if(!this.isValue(a))return!0;a=e.trim(a).replace(/\&nbsp\;/ig,"").replace(/\&#160\;/ig,"");return""===a},NumberFormat:function(a,b){var c=q.isNumber;c(a)||(a*=1);if(c(a)){var e=0>a,d=String(a),g=b.decimalSeparator||".";if(c(b.decimalPlaces)){var k=b.decimalPlaces,
d=Math.pow(10,k),d=String(Math.round(a*d)/d),c=d.lastIndexOf(".");if(0<k)for(0>c?(d+=g,c=d.length-1):"."!==g&&(d=d.replace(".",g));d.length-1-c<k;)d+="0"}if(b.thousandsSeparator){var k=b.thousandsSeparator,c=d.lastIndexOf(g),c=-1<c?c:d.length,g=void 0===b.decimalSeparator?"":d.substring(c),h=-1,m;for(m=c;0<m;m--)h++,0===h%3&&m!==c&&(!e||1<m)&&(g=k+g),g=d.charAt(m-1)+g;d=g}return d}return a}});var l=function(a,b,c,f,d){var g=b;c=e.extend({},w.call(e(this),"formatter"),c);try{g=e.fn.fmatter[a].call(this,
b,c,f,d)}catch(k){}return g};e.fn.fmatter=l;l.getCellBuilder=function(a,b,c){a=null!=e.fn.fmatter[a]?e.fn.fmatter[a].getCellBuilder:null;return e.isFunction(a)?a.call(this,e.extend({},w.call(e(this),"formatter"),b),c):null};l.defaultFormat=function(a,b){return q.isValue(a)&&""!==a?a:b.defaultValue||"&#160;"};var t=l.defaultFormat;l.email=function(a,b){return q.isEmpty(a)?t(a,b):'<a href="mailto:'+a+'">'+a+"</a>"};l.checkbox=function(a,b){var c=b.colModel,f=e.extend({},b.checkbox);null!=c&&(f=e.extend({},
f,c.formatoptions||{}));c=!0===f.disabled?'disabled="disabled"':"";if(q.isEmpty(a)||void 0===a)a=t(a,f);a=String(a);a=String(a).toLowerCase();return'<input type="checkbox" '+(0>a.search(/(false|f|0|no|n|off|undefined)/i)?" checked='checked' ":"")+' value="'+a+'" data-offval="no" '+c+"/>"};l.checkbox.getCellBuilder=function(a){var b=a.colModel,c=e.extend({},a.checkbox),f;null!=b&&(c=e.extend({},c,b.formatoptions||{}));f='" data-offval="no" '+(!0===c.disabled?'disabled="disabled"':"")+"/>";return function(a){if(q.isEmpty(a)||
void 0===a)a=t(a,c);a=String(a).toLowerCase();return'<input type="checkbox" '+(0>a.search(/(false|f|0|no|n|off|undefined)/i)?" checked='checked' ":"")+' value="'+a+f}};l.checkboxFontAwesome4=function(a,b){var c=b.colModel,e=!1!==c.title?' title="'+(b.colName||c.label||c.name)+'"':"",d=String(a).toLowerCase(),c=c.editoptions||{},c="string"===typeof c.value?c.value.split(":")[0]:"yes";return 1===a||"1"===d||"x"===d||!0===a||"true"===d||"yes"===d||d===c?'<i class="fa fa-check-square-o fa-lg"'+e+"></i>":
'<i class="fa fa-square-o fa-lg"'+e+"></i>"};l.checkboxFontAwesome4.getCellBuilder=function(a){var b=a.colModel;a=!1!==b.title?' title="'+(a.colName||b.label||b.name)+'"':"";var b=b.editoptions||{},c="string"===typeof b.value?b.value.split(":")[0]:"yes",e='<i class="fa fa-check-square-o fa-lg"'+a+"></i>",d='<i class="fa fa-square-o fa-lg"'+a+"></i>";return function(a){var b=String(a).toLowerCase();return!0===a||1===a||"1"===b||"x"===b||"true"===b||"yes"===b||b===c?e:d}};l.checkboxFontAwesome4.unformat=
function(a,b,c){a=b.colModel.editoptions||{};a="string"===typeof a.value?a.value.split(":"):["Yes","No"];return e(">i",c).hasClass("fa-check-square-o")?a[0]:a[1]};l.link=function(a,b){var c=b.colModel,f="",d={target:b.target};null!=c&&(d=e.extend({},d,c.formatoptions||{}));d.target&&(f="target="+d.target);return q.isEmpty(a)?t(a,d):"<a "+f+' href="'+a+'">'+a+"</a>"};l.showlink=function(a,b,c){var f=this,d=b.colModel,g={baseLinkUrl:b.baseLinkUrl,showAction:b.showAction,addParam:b.addParam||"",target:b.target,
idName:b.idName,hrefDefaultValue:"#"},k="",h,m,n=function(d){return e.isFunction(d)?d.call(f,{cellValue:a,rowid:b.rowId,rowData:c,options:g}):d||""};null!=d&&(g=e.extend({},g,d.formatoptions||{}));g.target&&(k="target="+n(g.target));d=n(g.baseLinkUrl)+n(g.showAction);h=g.idName?encodeURIComponent(n(g.idName))+"="+encodeURIComponent(n(g.rowId)||b.rowId):"";m=n(g.addParam);"object"===typeof m&&null!==m&&(m=(""!==h?"&":"")+e.param(m));d+=h||m?"?"+h+m:"";""===d&&(d=n(g.hrefDefaultValue));return"string"===
typeof a||q.isNumber(a)||e.isFunction(g.cellValue)?"<a "+k+' href="'+d+'">'+(e.isFunction(g.cellValue)?n(g.cellValue):a)+"</a>":t(a,g)};l.showlink.getCellBuilder=function(a){var b={baseLinkUrl:a.baseLinkUrl,showAction:a.showAction,addParam:a.addParam||"",target:a.target,idName:a.idName,hrefDefaultValue:"#"};a=a.colModel;null!=a&&(b=e.extend({},b,a.formatoptions||{}));return function(a,f,d){var g=this,k=f.rowId,h="",m,n,u=function(f){return e.isFunction(f)?f.call(g,{cellValue:a,rowid:k,rowData:d,options:b}):
f||""};b.target&&(h="target="+u(b.target));m=u(b.baseLinkUrl)+u(b.showAction);f=b.idName?encodeURIComponent(u(b.idName))+"="+encodeURIComponent(u(k)||f.rowId):"";n=u(b.addParam);"object"===typeof n&&null!==n&&(n=(""!==f?"&":"")+e.param(n));m+=f||n?"?"+f+n:"";""===m&&(m=u(b.hrefDefaultValue));return"string"===typeof a||q.isNumber(a)||e.isFunction(b.cellValue)?"<a "+h+' href="'+m+'">'+(e.isFunction(b.cellValue)?u(b.cellValue):a)+"</a>":t(a,b)}};l.showlink.pageFinalization=function(a){var b=e(this),
c=this.p,f=c.colModel[a],d,g=this.rows,k=g.length,h,m=function(c){var d=e(this).closest(".jqgrow");if(0<d.length)return f.formatoptions.onClick.call(b[0],{iCol:a,iRow:d[0].rowIndex,rowid:d.attr("id"),cm:f,cmName:f.name,cellValue:e(this).text(),a:this,event:c})};if(null!=f.formatoptions&&e.isFunction(f.formatoptions.onClick))for(d=0;d<k;d++)h=g[d],e(h).hasClass("jqgrow")&&(h=h.cells[a],f.autoResizable&&null!=h&&e(h.firstChild).hasClass(c.autoResizing.wrapperClassName)&&(h=h.firstChild),e(h.firstChild).bind("click",
m))};var y=function(a,b){a=b.prefix?b.prefix+a:a;return b.suffix?a+b.suffix:a},z=function(a,b,c){var f=b.colModel;b=e.extend({},b[c]);null!=f&&(b=e.extend({},b,f.formatoptions||{}));return q.isEmpty(a)?y(b.defaultValue,b):y(q.NumberFormat(a,b),b)};l.integer=function(a,b){return z(a,b,"integer")};l.number=function(a,b){return z(a,b,"number")};l.currency=function(a,b){return z(a,b,"currency")};var A=function(a,b){var c=a.colModel,f=e.extend({},a[b]);null!=c&&(f=e.extend({},f,c.formatoptions||{}));var d=
q.NumberFormat,g=f.defaultValue?y(f.defaultValue,f):"";return function(a){return q.isEmpty(a)?g:y(d(a,f),f)}};l.integer.getCellBuilder=function(a){return A(a,"integer")};l.number.getCellBuilder=function(a){return A(a,"number")};l.currency.getCellBuilder=function(a){return A(a,"currency")};l.date=function(a,b,c,f){c=b.colModel;b=e.extend({},b.date);null!=c&&(b=e.extend({},b,c.formatoptions||{}));return b.reformatAfterEdit||"edit"!==f?q.isEmpty(a)?t(a,b):p.parseDate.call(this,b.srcformat,a,b.newformat,
b):t(a,b)};l.date.getCellBuilder=function(a,b){var c=e.extend({},a.date);null!=a.colModel&&(c=e.extend({},c,a.colModel.formatoptions||{}));var f=p.parseDate,d=c.srcformat,g=c.newformat;return c.reformatAfterEdit||"edit"!==b?function(a){return q.isEmpty(a)?t(a,c):f.call(this,d,a,g,c)}:function(a){return t(a,c)}};l.select=function(a,b){var c=[],f=b.colModel,d,f=e.extend({},f.editoptions||{},f.formatoptions||{}),g=f.value,k=f.separator||":",h=f.delimiter||";";if(g){var m=!0===f.multiple?!0:!1,n=[],l=
function(a,b){if(0<b)return a};m&&(n=e.map(String(a).split(","),function(a){return e.trim(a)}));if("string"===typeof g){var v=g.split(h),r,x;for(r=0;r<v.length;r++)if(h=v[r].split(k),2<h.length&&(h[1]=e.map(h,l).join(k)),x=e.trim(h[0]),f.defaultValue===x&&(d=h[1]),m)-1<e.inArray(x,n)&&c.push(h[1]);else if(x===e.trim(a)){c=[h[1]];break}}else q.isObject(g)&&(d=g[f.defaultValue],c=m?e.map(n,function(a){return g[a]}):[void 0===g[a]?"":g[a]])}a=c.join(", ");return""!==a?a:void 0!==f.defaultValue?d:t(a,
f)};l.select.getCellBuilder=function(a){a=a.colModel;var b=l.defaultFormat,c=e.extend({},a.editoptions||{},a.formatoptions||{}),f=c.value;a=c.separator||":";var d=c.delimiter||";",g,k=void 0!==c.defaultValue,h=!0===c.multiple?!0:!1,m,n={},u=function(a,b){if(0<b)return a};if("string"===typeof f)for(f=f.split(d),d=f.length,m=d-1;0<=m;m--)d=f[m].split(a),2<d.length&&(d[1]=e.map(d,u).join(a)),n[e.trim(d[0])]=d[1];else if(q.isObject(f))n=f;else return function(a){return a?String(a):b(a,c)};k&&(g=n[c.defaultValue]);
return h?function(a){var d=[],f,h=e.map(String(a).split(","),function(a){return e.trim(a)});for(f=0;f<h.length;f++)a=h[f],n.hasOwnProperty(a)&&d.push(n[a]);a=d.join(", ");return""!==a?a:k?g:b(a,c)}:function(a){var d=n[String(a)];return""!==d&&void 0!==d?d:k?g:b(a,c)}};l.rowactions=function(a,b){var c=e(this).closest("tr.jqgrow"),f=c.attr("id"),d=e(this).closest("table.ui-jqgrid-btable").attr("id").replace(/_frozen([^_]*)$/,"$1"),g=e("#"+p.jqID(d)),d=g[0],k=d.p,h=k.colModel[p.getCellIndex(this)],h=
e.extend(!0,{extraparam:{}},p.actionsNav||{},k.actionsNavOptions||{},h.formatoptions||{});void 0!==k.editOptions&&(h.editOptions=e.extend(!0,h.editOptions||{},k.editOptions));void 0!==k.delOptions&&(h.delOptions=k.delOptions);c.hasClass("jqgrid-new-row")&&(h.extraparam[k.prmNames.oper]=k.prmNames.addoper);var m={keys:h.keys,oneditfunc:h.onEdit,successfunc:h.onSuccess,url:h.url,extraparam:h.extraparam,aftersavefunc:h.afterSave,errorfunc:h.onError,afterrestorefunc:h.afterRestore,restoreAfterError:h.restoreAfterError,
mtype:h.mtype};!k.multiselect&&f!==k.selrow||k.multiselect&&0>e.inArray(f,k.selarrrow)?g.jqGrid("setSelection",f,!0,a):p.fullBoolFeedback.call(d,"onSelectRow","jqGridSelectRow",f,!0,a);switch(b){case "edit":g.jqGrid("editRow",f,m);break;case "save":g.jqGrid("saveRow",f,m);break;case "cancel":g.jqGrid("restoreRow",f,h.afterRestore);break;case "del":h.delOptions=h.delOptions||{};void 0===h.delOptions.top&&(h.delOptions.top=c.offset().top+c.outerHeight()-g.closest(".ui-jqgrid").offset().top);g.jqGrid("delGridRow",
f,h.delOptions);break;case "formedit":h.editOptions=h.editOptions||{};void 0===h.editOptions.top&&(h.editOptions.top=c.offset().top+c.outerHeight()-g.closest(".ui-jqgrid").offset().top,h.editOptions.recreateForm=!0);g.jqGrid("editGridRow",f,h.editOptions);break;default:if(null!=h.custom&&0<h.custom.length)for(g=h.custom.length,c=0;c<g;c++)k=h.custom[c],k.action===b&&e.isFunction(k.onClick)&&k.onClick.call(d,{rowid:f,event:a,action:b,options:k})}a.stopPropagation&&a.stopPropagation();return!1};l.actions=
function(a,b,c,f){a=b.rowId;var d="",g=this.p,k=e(this),h={},m=w.call(k,"edit")||{},k=e.extend({editbutton:!0,delbutton:!0,editformbutton:!1,commonIconClass:"ui-icon",editicon:"ui-icon-pencil",delicon:"ui-icon-trash",saveicon:"ui-icon-disk",cancelicon:"ui-icon-cancel",savetitle:m.bSubmit||"",canceltitle:m.bCancel||""},w.call(k,"nav")||{},p.nav||{},g.navOptions||{},w.call(k,"actionsNav")||{},p.actionsNav||{},g.actionsNavOptions||{},b.colModel.formatoptions||{}),m=p.mergeCssClasses,g=m(p.getRes(p.guiStyles[g.guiStyle],
"states.hover")),g="onmouseover=\"jQuery(this).addClass('"+g+"');\" onmouseout=\"jQuery(this).removeClass('"+g+"');\"",n=[{action:"edit",actionName:"formedit",display:k.editformbutton},{action:"edit",display:!k.editformbutton&&k.editbutton},{action:"del",idPrefix:"Delete",display:k.delbutton},{action:"save",display:k.editformbutton||k.editbutton,hidden:!0},{action:"cancel",display:k.editformbutton||k.editbutton,hidden:!0}],l=null!=k.custom?k.custom.length-1:-1;if(void 0===a||q.isEmpty(a))return"";
if(e.isFunction(k.isDisplayButtons))try{h=k.isDisplayButtons.call(this,b,c,f)||{}}catch(x){}for(;0<=l;)b=k.custom[l--],n["first"===b.position?"unshift":"push"](b);b=0;for(l=n.length;b<l;b++)if(c=e.extend({},n[b],h[n[b].action]||{}),!1!==c.display){f=c.action;var v=c.actionName||f,r=void 0!==c.idPrefix?c.idPrefix:f.charAt(0).toUpperCase()+f.substring(1);c="<div title='"+k[f+"title"]+(c.hidden?"' style='display:none;":"")+"' class='ui-pg-div ui-inline-"+f+"' "+(null!==r?"id='j"+r+"Button_"+a:"")+"' onclick=\"return jQuery.fn.fmatter.rowactions.call(this,event,'"+
v+"');\" "+(c.noHovering?"":g)+"><span class='"+m(k.commonIconClass,k[f+"icon"])+"'></span></div>";d+=c}return"<div class='ui-jqgrid-actions'>"+d+"</div>"};l.actions.pageFinalization=function(a){var b=e(this),c=this.p,f=c.colModel,d=f[a],g=function(g,h){var k=0,l,r;l=f.length;for(r=0;r<l&&!0===f[r].frozen;r++)k=r;l=b.jqGrid("getGridRowById",h);null!=l&&null!=l.cells&&(a=c.iColByName[d.name],r=e(l.cells[a]).children(".ui-jqgrid-actions"),d.frozen&&c.frozenColumns&&a<=k&&(r=r.add(e(b[0].grid.fbRows[l.rowIndex].cells[a]).children(".ui-jqgrid-actions"))),
g?(r.find(">.ui-inline-edit,>.ui-inline-del").show(),r.find(">.ui-inline-save,>.ui-inline-cancel").hide()):(r.find(">.ui-inline-edit,>.ui-inline-del").hide(),r.find(">.ui-inline-save,>.ui-inline-cancel").show()))},k=function(a,b){g(!0,b);return!1},h=function(a,b){g(!1,b);return!1};null!=d.formatoptions&&d.formatoptions.editformbutton||(b.unbind("jqGridInlineAfterRestoreRow.jqGridFormatter jqGridInlineAfterSaveRow.jqGridFormatter",k),b.bind("jqGridInlineAfterRestoreRow.jqGridFormatter jqGridInlineAfterSaveRow.jqGridFormatter",
k),b.unbind("jqGridInlineEditRow.jqGridFormatter",h),b.bind("jqGridInlineEditRow.jqGridFormatter",h))};e.unformat=function(a,b,c,f){var d,g=b.colModel,k=g.formatter,h=this.p,m=g.formatoptions||{},n=g.unformat||l[k]&&l[k].unformat;a instanceof jQuery&&0<a.length&&(a=a[0]);h.treeGrid&&null!=a&&e(a.firstChild).hasClass("tree-wrap")&&(e(a.lastChild).hasClass("cell-wrapper")||e(a.lastChild).hasClass("cell-wrapperleaf"))&&(a=a.lastChild);g.autoResizable&&null!=a&&e(a.firstChild).hasClass(h.autoResizing.wrapperClassName)&&
(a=a.firstChild);if(void 0!==n&&e.isFunction(n))d=n.call(this,e(a).text(),b,a);else if(void 0!==k&&"string"===typeof k){var q=e(this),v=function(a,b){return void 0!==m[b]?m[b]:w.call(q,"formatter."+a+"."+b)},h=function(a,b){var c=v(a,"thousandsSeparator").replace(/([\.\*\_\'\(\)\{\}\+\?\\])/g,"\\$1");return b.replace(new RegExp(c,"g"),"")};switch(k){case "integer":d=h("integer",e(a).text());break;case "number":d=h("number",e(a).text()).replace(v("number","decimalSeparator"),".");break;case "currency":d=
e(a).text();b=v("currency","prefix");c=v("currency","suffix");b&&b.length&&(d=d.substr(b.length));c&&c.length&&(d=d.substr(0,d.length-c.length));d=h("number",d).replace(v("number","decimalSeparator"),".");break;case "checkbox":d=null!=g.editoptions&&"string"===typeof g.editoptions.value?g.editoptions.value.split(":"):["Yes","No"];d=e("input",a).is(":checked")?d[0]:d[1];break;case "select":d=e.unformat.select(a,b,c,f);break;case "actions":return"";default:d=e(a).text()}}return d=void 0!==d?d:!0===
f?e(a).text():p.htmlDecode(e(a).html())};e.unformat.select=function(a,b,c,f){c=[];a=e(a).text();b=b.colModel;if(!0===f)return a;b=e.extend({},b.editoptions||{},b.formatoptions||{});f=void 0===b.separator?":":b.separator;var d=void 0===b.delimiter?";":b.delimiter;if(b.value){var g=b.value;b=!0===b.multiple?!0:!1;var k=[],h=function(a,b){if(0<b)return a};b&&(k=a.split(","),k=e.map(k,function(a){return e.trim(a)}));if("string"===typeof g){var m=g.split(d),l=0,p;for(p=0;p<m.length;p++)if(d=m[p].split(f),
2<d.length&&(d[1]=e.map(d,h).join(f)),b)-1<e.inArray(e.trim(d[1]),k)&&(c[l]=d[0],l++);else if(e.trim(d[1])===e.trim(a)){c[0]=d[0];break}}else if(q.isObject(g)||e.isArray(g))b||(k[0]=a),c=e.map(k,function(a){var b;e.each(g,function(c,d){if(d===a)return b=c,!1});if(void 0!==b)return b});return c.join(", ")}return a||""};e.unformat.date=function(a,b){var c=e.extend(!0,{},w.call(e(this),"formatter.date"),p.formatter.date||{},b.formatoptions||{});return q.isEmpty(a)?"":p.parseDate.call(this,c.newformat,
a,c.srcformat,c)}});
/*
//# sourceMappingURL=jquery.fmatter.map
*/